package main

// `clawpatrol test <config> <file-or-dir>` — replay recorded gateway
// actions against a candidate policy and report any verdict
// differences. Pure CLI: no gateway, no DB, no auth. See site/doc/clawpatrol-test.md.

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/denoland/clawpatrol/config"
	"github.com/denoland/clawpatrol/config/extplugin"
	"github.com/denoland/clawpatrol/config/runtime"
)

const testUsage = `usage: clawpatrol test <config.hcl> <fixture.json | fixture-dir>

Replay recorded gateway actions against a candidate HCL policy and
report any verdict drift. Use it to verify a policy change doesn't
accidentally allow or deny something it shouldn't.

Fixtures are JSON files generated by the dashboard's "Download
action" button. See https://clawpatrol.dev/docs/clawpatrol-test for
the format, the local capture workflow, and CI integration.

Exit 0 when every fixture matches; 1 on mismatch or fixture load
error; 2 on usage / config-load error.`

// runTest is the CLI entry: prints any output to stdout/stderr and
// exits with the right code. The pure logic lives in testCmd so the
// integration tests can drive it without touching stdio.
func runTest(args []string) {
	stdout, stderr, code := testCmd(args)
	if stdout != "" {
		fmt.Println(stdout)
	}
	if stderr != "" {
		fmt.Fprintln(os.Stderr, stderr)
	}
	os.Exit(code)
}

// testCmd loads the candidate policy, resolves the fixture path
// argument, replays each fixture, and reports mismatches. Exit codes:
// 0 ok (all fixtures matched), 1 verdict mismatch or load error on a
// fixture, 2 usage / config-load error.
func testCmd(args []string) (stdout, stderr string, code int) {
	for _, a := range args {
		if a == "-h" || a == "--help" {
			return testUsage, "", 0
		}
	}
	if len(args) != 2 {
		return "", testUsage, 2
	}
	cfgPath, target := args[0], args[1]

	config.SetPluginLoader(extplugin.New(nil))
	_, policy, err := loadConfig(cfgPath)
	if err != nil {
		return "", fmt.Sprintf("load config: %v", err), 2
	}

	files, err := resolveFixtures(target)
	if err != nil {
		return "", fmt.Sprintf("resolve fixtures: %v", err), 2
	}
	if len(files) == 0 {
		return "", fmt.Sprintf("no .json fixtures under %s", target), 2
	}

	var out strings.Builder
	mismatches := 0
	for _, f := range files {
		ok, msg, err := runOneFixture(policy, f)
		switch {
		case err != nil:
			fmt.Fprintf(&out, "FAIL %s: %v\n", f, err)
			mismatches++
		case !ok:
			fmt.Fprintf(&out, "FAIL %s\n", f)
			out.WriteString(msg)
			mismatches++
		default:
			fmt.Fprintf(&out, "ok   %s\n", f)
		}
	}
	fmt.Fprintf(&out, "%d action(s) checked, %d mismatch(es)\n", len(files), mismatches)
	final := strings.TrimRight(out.String(), "\n")
	if mismatches > 0 {
		return "", final, 1
	}
	return final, "", 0
}

func resolveFixtures(target string) ([]string, error) {
	st, err := os.Stat(target)
	if err != nil {
		return nil, err
	}
	if !st.IsDir() {
		return []string{target}, nil
	}
	matches, err := filepath.Glob(filepath.Join(target, "*.json"))
	if err != nil {
		return nil, err
	}
	sort.Strings(matches)
	return matches, nil
}

// runOneFixture loads one fixture, dispatches it through the compiled
// policy, and returns (matched?, mismatch-diff, err). err is non-nil
// for load / setup failures; (false, diff, nil) is a clean verdict
// mismatch.
func runOneFixture(policy *config.CompiledPolicy, path string) (bool, string, error) {
	body, err := os.ReadFile(path)
	if err != nil {
		return false, "", err
	}
	var f Fixture
	if err := json.Unmarshal(body, &f); err != nil {
		return false, "", err
	}
	ep, err := f.ResolveEndpoint(policy)
	if err != nil {
		return false, "", err
	}
	if f.Match.Verdict == "passthrough" {
		return false, "", fmt.Errorf(
			"passthrough fixtures aren't yet replayable — pin to a named endpoint or remove",
		)
	}

	family, err := fixtureFamily(&f, ep)
	if err != nil {
		return false, "", err
	}

	var parseSQL func(string) any
	if p, ok := ep.Plugin.Runtime.(runtime.SQLParser); ok {
		parseSQL = p.ParseStatement
	}
	req, err := f.ToMatchRequest(family, parseSQL)
	if err != nil {
		return false, "", err
	}
	cr := runtime.MatchRequest(ep, req)
	got := MatchFromCompiledRule(cr, ep)

	if matchEquals(got, f.Match) {
		return true, "", nil
	}
	return false, formatMismatch(got, f.Match), nil
}

// matchEquals compares the runner's produced match against the
// fixture's asserted match. Reason is informational and not part of
// the comparison — it drifts under safe edits.
func matchEquals(got, want Match) bool {
	if got.Verdict != want.Verdict || got.Rule != want.Rule {
		return false
	}
	// Endpoint assertion is optional: an empty want.Endpoint means
	// the fixture didn't pin an endpoint, so don't fail on it.
	if want.Endpoint != "" && got.Endpoint != want.Endpoint {
		return false
	}
	return true
}

func fixtureFamily(f *Fixture, ep *config.CompiledEndpoint) (string, error) {
	switch {
	case f.Action.HTTP != nil:
		if ep.Family != "http" {
			return "", fmt.Errorf("endpoint %q is family %q but fixture has http block", ep.Name, ep.Family)
		}
		return "http", nil
	case f.Action.K8s != nil:
		if ep.Family != "k8s" {
			return "", fmt.Errorf("endpoint %q is family %q but fixture has k8s block", ep.Name, ep.Family)
		}
		return "k8s", nil
	case f.Action.SQL != nil:
		if ep.Family != "sql" {
			return "", fmt.Errorf("endpoint %q is family %q but fixture has sql block", ep.Name, ep.Family)
		}
		return "sql", nil
	}
	return "", fmt.Errorf("fixture has no family block")
}

func formatMismatch(got, want Match) string {
	var b strings.Builder
	fmt.Fprintf(&b, "  want verdict=%-12q rule=%-30q endpoint=%q\n", want.Verdict, want.Rule, want.Endpoint)
	fmt.Fprintf(&b, "  got  verdict=%-12q rule=%-30q endpoint=%q\n", got.Verdict, got.Rule, got.Endpoint)
	if got.Reason != "" && got.Reason != want.Reason {
		fmt.Fprintf(&b, "  reason: %s\n", strings.TrimSpace(got.Reason))
	}
	return b.String()
}
