// Plugin protocol v1 for clawpatrol's Terraform-style external plugins.
//
// One subprocess per plugin source. The gateway spawns the subprocess
// via hashicorp/go-plugin, fetches its Manifest, and registers virtual
// *config.Plugin entries for each declared (credential / tunnel /
// endpoint) type. At request time the gateway hands inbound conns to
// the plugin over the HandleConn bidi stream; endpoints that need an
// upstream connection through a tunnel go through Dial.
//
// The plugin is responsible for parsing whatever protocol rides on
// the bytes it receives. The gateway only optionally terminates TLS
// before handing the bytes over.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.2
// source: plugin.proto

package extpluginpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Plugin_Manifest_FullMethodName = "/clawpatrol.plugin.v1.Plugin/Manifest"
	Plugin_Build_FullMethodName    = "/clawpatrol.plugin.v1.Plugin/Build"
)

// PluginClient is the client API for Plugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginClient interface {
	// Manifest is called once on plugin startup. The plugin reports the
	// credential / tunnel / endpoint types it provides plus their HCL
	// schemas. The gateway converts each entry into a virtual
	// *config.Plugin and registers it.
	Manifest(ctx context.Context, in *ManifestRequest, opts ...grpc.CallOption) (*ManifestResponse, error)
	// Build is called once per HCL block during config load. The gateway
	// sends the decoded block body as a JSON object; the plugin
	// validates, normalizes, and returns canonical JSON that round-trips
	// back to the plugin in ConnInit / OpenTunnelRequest. Diagnostics
	// are reported back to the user with the block's source range.
	Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*BuildResponse, error)
}

type pluginClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginClient(cc grpc.ClientConnInterface) PluginClient {
	return &pluginClient{cc}
}

func (c *pluginClient) Manifest(ctx context.Context, in *ManifestRequest, opts ...grpc.CallOption) (*ManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManifestResponse)
	err := c.cc.Invoke(ctx, Plugin_Manifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*BuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildResponse)
	err := c.cc.Invoke(ctx, Plugin_Build_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServer is the server API for Plugin service.
// All implementations must embed UnimplementedPluginServer
// for forward compatibility.
type PluginServer interface {
	// Manifest is called once on plugin startup. The plugin reports the
	// credential / tunnel / endpoint types it provides plus their HCL
	// schemas. The gateway converts each entry into a virtual
	// *config.Plugin and registers it.
	Manifest(context.Context, *ManifestRequest) (*ManifestResponse, error)
	// Build is called once per HCL block during config load. The gateway
	// sends the decoded block body as a JSON object; the plugin
	// validates, normalizes, and returns canonical JSON that round-trips
	// back to the plugin in ConnInit / OpenTunnelRequest. Diagnostics
	// are reported back to the user with the block's source range.
	Build(context.Context, *BuildRequest) (*BuildResponse, error)
	mustEmbedUnimplementedPluginServer()
}

// UnimplementedPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginServer struct{}

func (UnimplementedPluginServer) Manifest(context.Context, *ManifestRequest) (*ManifestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Manifest not implemented")
}
func (UnimplementedPluginServer) Build(context.Context, *BuildRequest) (*BuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Build not implemented")
}
func (UnimplementedPluginServer) mustEmbedUnimplementedPluginServer() {}
func (UnimplementedPluginServer) testEmbeddedByValue()                {}

// UnsafePluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServer will
// result in compilation errors.
type UnsafePluginServer interface {
	mustEmbedUnimplementedPluginServer()
}

func RegisterPluginServer(s grpc.ServiceRegistrar, srv PluginServer) {
	// If the following call panics, it indicates UnimplementedPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Plugin_ServiceDesc, srv)
}

func _Plugin_Manifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Manifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_Manifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Manifest(ctx, req.(*ManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Build_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Build(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_Build_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Build(ctx, req.(*BuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Plugin_ServiceDesc is the grpc.ServiceDesc for Plugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Plugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clawpatrol.plugin.v1.Plugin",
	HandlerType: (*PluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Manifest",
			Handler:    _Plugin_Manifest_Handler,
		},
		{
			MethodName: "Build",
			Handler:    _Plugin_Build_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

const (
	Credential_InjectHTTP_FullMethodName    = "/clawpatrol.plugin.v1.Credential/InjectHTTP"
	Credential_TransformHTTP_FullMethodName = "/clawpatrol.plugin.v1.Credential/TransformHTTP"
)

// CredentialClient is the client API for Credential service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CredentialClient interface {
	// InjectHTTP lets an external credential type participate in the
	// built-in HTTPS endpoint's request-time credential injection path.
	// Header-only: the request body never flows through the plugin.
	InjectHTTP(ctx context.Context, in *InjectHTTPRequest, opts ...grpc.CallOption) (*InjectHTTPResponse, error)
	// TransformHTTP is the streaming superset for credentials that declared
	// http_transform: ones that rewrite the request method / URL / body,
	// not just headers (AWS SigV4 over the body, telegram/discord secrets
	// carried in the URL or body).
	//
	// The gateway sends a TransformHTTPInit, then streams the request body
	// as HTTPBodyChunk frames (ending eof=true). The plugin reads as much
	// as it needs — buffering is the plugin's choice — then sends exactly
	// one TransformHTTPHead (header / method / URL mutations) followed by
	// the transformed body as HTTPBodyChunk frames. The gateway applies the
	// head before forwarding upstream (a body-derived header like a SigV4
	// signature is finalized first), then pipes the plugin's body chunks on
	// to the upstream. A plugin that doesn't touch the body just copies the
	// input chunks straight to its output (no buffering).
	TransformHTTP(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TransformHTTPUp, TransformHTTPDown], error)
}

type credentialClient struct {
	cc grpc.ClientConnInterface
}

func NewCredentialClient(cc grpc.ClientConnInterface) CredentialClient {
	return &credentialClient{cc}
}

func (c *credentialClient) InjectHTTP(ctx context.Context, in *InjectHTTPRequest, opts ...grpc.CallOption) (*InjectHTTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InjectHTTPResponse)
	err := c.cc.Invoke(ctx, Credential_InjectHTTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialClient) TransformHTTP(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TransformHTTPUp, TransformHTTPDown], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Credential_ServiceDesc.Streams[0], Credential_TransformHTTP_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TransformHTTPUp, TransformHTTPDown]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Credential_TransformHTTPClient = grpc.BidiStreamingClient[TransformHTTPUp, TransformHTTPDown]

// CredentialServer is the server API for Credential service.
// All implementations must embed UnimplementedCredentialServer
// for forward compatibility.
type CredentialServer interface {
	// InjectHTTP lets an external credential type participate in the
	// built-in HTTPS endpoint's request-time credential injection path.
	// Header-only: the request body never flows through the plugin.
	InjectHTTP(context.Context, *InjectHTTPRequest) (*InjectHTTPResponse, error)
	// TransformHTTP is the streaming superset for credentials that declared
	// http_transform: ones that rewrite the request method / URL / body,
	// not just headers (AWS SigV4 over the body, telegram/discord secrets
	// carried in the URL or body).
	//
	// The gateway sends a TransformHTTPInit, then streams the request body
	// as HTTPBodyChunk frames (ending eof=true). The plugin reads as much
	// as it needs — buffering is the plugin's choice — then sends exactly
	// one TransformHTTPHead (header / method / URL mutations) followed by
	// the transformed body as HTTPBodyChunk frames. The gateway applies the
	// head before forwarding upstream (a body-derived header like a SigV4
	// signature is finalized first), then pipes the plugin's body chunks on
	// to the upstream. A plugin that doesn't touch the body just copies the
	// input chunks straight to its output (no buffering).
	TransformHTTP(grpc.BidiStreamingServer[TransformHTTPUp, TransformHTTPDown]) error
	mustEmbedUnimplementedCredentialServer()
}

// UnimplementedCredentialServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCredentialServer struct{}

func (UnimplementedCredentialServer) InjectHTTP(context.Context, *InjectHTTPRequest) (*InjectHTTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InjectHTTP not implemented")
}
func (UnimplementedCredentialServer) TransformHTTP(grpc.BidiStreamingServer[TransformHTTPUp, TransformHTTPDown]) error {
	return status.Error(codes.Unimplemented, "method TransformHTTP not implemented")
}
func (UnimplementedCredentialServer) mustEmbedUnimplementedCredentialServer() {}
func (UnimplementedCredentialServer) testEmbeddedByValue()                    {}

// UnsafeCredentialServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CredentialServer will
// result in compilation errors.
type UnsafeCredentialServer interface {
	mustEmbedUnimplementedCredentialServer()
}

func RegisterCredentialServer(s grpc.ServiceRegistrar, srv CredentialServer) {
	// If the following call panics, it indicates UnimplementedCredentialServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Credential_ServiceDesc, srv)
}

func _Credential_InjectHTTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InjectHTTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialServer).InjectHTTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Credential_InjectHTTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialServer).InjectHTTP(ctx, req.(*InjectHTTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Credential_TransformHTTP_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CredentialServer).TransformHTTP(&grpc.GenericServerStream[TransformHTTPUp, TransformHTTPDown]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Credential_TransformHTTPServer = grpc.BidiStreamingServer[TransformHTTPUp, TransformHTTPDown]

// Credential_ServiceDesc is the grpc.ServiceDesc for Credential service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Credential_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clawpatrol.plugin.v1.Credential",
	HandlerType: (*CredentialServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InjectHTTP",
			Handler:    _Credential_InjectHTTP_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TransformHTTP",
			Handler:       _Credential_TransformHTTP_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "plugin.proto",
}

const (
	Endpoint_HandleConn_FullMethodName = "/clawpatrol.plugin.v1.Endpoint/HandleConn"
)

// EndpointClient is the client API for Endpoint service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EndpointClient interface {
	// HandleConn is a bidi stream owning one inbound agent connection.
	//
	// Gateway sends ConnInit first, then ConnData frames as bytes arrive
	// from the agent. ConnClose from either side terminates the session.
	//
	// Plugin sends ConnData frames for bytes to write back to the agent,
	// and may interleave ConnEvent messages (audit emits).
	HandleConn(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConnMessage, ConnMessage], error)
}

type endpointClient struct {
	cc grpc.ClientConnInterface
}

func NewEndpointClient(cc grpc.ClientConnInterface) EndpointClient {
	return &endpointClient{cc}
}

func (c *endpointClient) HandleConn(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConnMessage, ConnMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Endpoint_ServiceDesc.Streams[0], Endpoint_HandleConn_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConnMessage, ConnMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Endpoint_HandleConnClient = grpc.BidiStreamingClient[ConnMessage, ConnMessage]

// EndpointServer is the server API for Endpoint service.
// All implementations must embed UnimplementedEndpointServer
// for forward compatibility.
type EndpointServer interface {
	// HandleConn is a bidi stream owning one inbound agent connection.
	//
	// Gateway sends ConnInit first, then ConnData frames as bytes arrive
	// from the agent. ConnClose from either side terminates the session.
	//
	// Plugin sends ConnData frames for bytes to write back to the agent,
	// and may interleave ConnEvent messages (audit emits).
	HandleConn(grpc.BidiStreamingServer[ConnMessage, ConnMessage]) error
	mustEmbedUnimplementedEndpointServer()
}

// UnimplementedEndpointServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEndpointServer struct{}

func (UnimplementedEndpointServer) HandleConn(grpc.BidiStreamingServer[ConnMessage, ConnMessage]) error {
	return status.Error(codes.Unimplemented, "method HandleConn not implemented")
}
func (UnimplementedEndpointServer) mustEmbedUnimplementedEndpointServer() {}
func (UnimplementedEndpointServer) testEmbeddedByValue()                  {}

// UnsafeEndpointServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EndpointServer will
// result in compilation errors.
type UnsafeEndpointServer interface {
	mustEmbedUnimplementedEndpointServer()
}

func RegisterEndpointServer(s grpc.ServiceRegistrar, srv EndpointServer) {
	// If the following call panics, it indicates UnimplementedEndpointServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Endpoint_ServiceDesc, srv)
}

func _Endpoint_HandleConn_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EndpointServer).HandleConn(&grpc.GenericServerStream[ConnMessage, ConnMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Endpoint_HandleConnServer = grpc.BidiStreamingServer[ConnMessage, ConnMessage]

// Endpoint_ServiceDesc is the grpc.ServiceDesc for Endpoint service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Endpoint_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clawpatrol.plugin.v1.Endpoint",
	HandlerType: (*EndpointServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HandleConn",
			Handler:       _Endpoint_HandleConn_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "plugin.proto",
}

const (
	Tunnel_OpenTunnel_FullMethodName  = "/clawpatrol.plugin.v1.Tunnel/OpenTunnel"
	Tunnel_Dial_FullMethodName        = "/clawpatrol.plugin.v1.Tunnel/Dial"
	Tunnel_CloseTunnel_FullMethodName = "/clawpatrol.plugin.v1.Tunnel/CloseTunnel"
)

// TunnelClient is the client API for Tunnel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TunnelClient interface {
	// OpenTunnel asks the plugin to bring up one tunnel instance.
	// The plugin returns an opaque handle that the gateway uses in
	// subsequent Dial / CloseTunnel calls.
	OpenTunnel(ctx context.Context, in *OpenTunnelRequest, opts ...grpc.CallOption) (*OpenTunnelResponse, error)
	// Dial opens one upstream connection via an open tunnel. Bidi
	// stream pumps bytes between gateway and tunneled upstream.
	Dial(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DialMessage, DialMessage], error)
	// CloseTunnel tears down a tunnel handle.
	CloseTunnel(ctx context.Context, in *CloseTunnelRequest, opts ...grpc.CallOption) (*CloseTunnelResponse, error)
}

type tunnelClient struct {
	cc grpc.ClientConnInterface
}

func NewTunnelClient(cc grpc.ClientConnInterface) TunnelClient {
	return &tunnelClient{cc}
}

func (c *tunnelClient) OpenTunnel(ctx context.Context, in *OpenTunnelRequest, opts ...grpc.CallOption) (*OpenTunnelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenTunnelResponse)
	err := c.cc.Invoke(ctx, Tunnel_OpenTunnel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tunnelClient) Dial(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DialMessage, DialMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Tunnel_ServiceDesc.Streams[0], Tunnel_Dial_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DialMessage, DialMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tunnel_DialClient = grpc.BidiStreamingClient[DialMessage, DialMessage]

func (c *tunnelClient) CloseTunnel(ctx context.Context, in *CloseTunnelRequest, opts ...grpc.CallOption) (*CloseTunnelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseTunnelResponse)
	err := c.cc.Invoke(ctx, Tunnel_CloseTunnel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TunnelServer is the server API for Tunnel service.
// All implementations must embed UnimplementedTunnelServer
// for forward compatibility.
type TunnelServer interface {
	// OpenTunnel asks the plugin to bring up one tunnel instance.
	// The plugin returns an opaque handle that the gateway uses in
	// subsequent Dial / CloseTunnel calls.
	OpenTunnel(context.Context, *OpenTunnelRequest) (*OpenTunnelResponse, error)
	// Dial opens one upstream connection via an open tunnel. Bidi
	// stream pumps bytes between gateway and tunneled upstream.
	Dial(grpc.BidiStreamingServer[DialMessage, DialMessage]) error
	// CloseTunnel tears down a tunnel handle.
	CloseTunnel(context.Context, *CloseTunnelRequest) (*CloseTunnelResponse, error)
	mustEmbedUnimplementedTunnelServer()
}

// UnimplementedTunnelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTunnelServer struct{}

func (UnimplementedTunnelServer) OpenTunnel(context.Context, *OpenTunnelRequest) (*OpenTunnelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenTunnel not implemented")
}
func (UnimplementedTunnelServer) Dial(grpc.BidiStreamingServer[DialMessage, DialMessage]) error {
	return status.Error(codes.Unimplemented, "method Dial not implemented")
}
func (UnimplementedTunnelServer) CloseTunnel(context.Context, *CloseTunnelRequest) (*CloseTunnelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseTunnel not implemented")
}
func (UnimplementedTunnelServer) mustEmbedUnimplementedTunnelServer() {}
func (UnimplementedTunnelServer) testEmbeddedByValue()                {}

// UnsafeTunnelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TunnelServer will
// result in compilation errors.
type UnsafeTunnelServer interface {
	mustEmbedUnimplementedTunnelServer()
}

func RegisterTunnelServer(s grpc.ServiceRegistrar, srv TunnelServer) {
	// If the following call panics, it indicates UnimplementedTunnelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tunnel_ServiceDesc, srv)
}

func _Tunnel_OpenTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenTunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelServer).OpenTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tunnel_OpenTunnel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelServer).OpenTunnel(ctx, req.(*OpenTunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tunnel_Dial_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TunnelServer).Dial(&grpc.GenericServerStream[DialMessage, DialMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tunnel_DialServer = grpc.BidiStreamingServer[DialMessage, DialMessage]

func _Tunnel_CloseTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseTunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelServer).CloseTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tunnel_CloseTunnel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelServer).CloseTunnel(ctx, req.(*CloseTunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Tunnel_ServiceDesc is the grpc.ServiceDesc for Tunnel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tunnel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clawpatrol.plugin.v1.Tunnel",
	HandlerType: (*TunnelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenTunnel",
			Handler:    _Tunnel_OpenTunnel_Handler,
		},
		{
			MethodName: "CloseTunnel",
			Handler:    _Tunnel_CloseTunnel_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Dial",
			Handler:       _Tunnel_Dial_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "plugin.proto",
}

const (
	HostState_Get_FullMethodName = "/clawpatrol.plugin.v1.HostState/Get"
	HostState_Put_FullMethodName = "/clawpatrol.plugin.v1.HostState/Put"
)

// HostStateClient is the client API for HostState service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HostState is a persistent, per-plugin byte store. It lets a sandboxed
// plugin remember opaque bytes across restarts (SSH host keys, signing
// material, a dynamic client_id) without a writable filesystem. The
// gateway namespaces every entry by the calling plugin, so one plugin
// can never read or write another's keys; the namespace is gateway-
// assigned, never sent by the plugin.
type HostStateClient interface {
	// Get returns the stored value for key, or found=false.
	Get(ctx context.Context, in *StateGetRequest, opts ...grpc.CallOption) (*StateGetResponse, error)
	// Put stores value under key, overwriting any previous value.
	Put(ctx context.Context, in *StatePutRequest, opts ...grpc.CallOption) (*StatePutResponse, error)
}

type hostStateClient struct {
	cc grpc.ClientConnInterface
}

func NewHostStateClient(cc grpc.ClientConnInterface) HostStateClient {
	return &hostStateClient{cc}
}

func (c *hostStateClient) Get(ctx context.Context, in *StateGetRequest, opts ...grpc.CallOption) (*StateGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StateGetResponse)
	err := c.cc.Invoke(ctx, HostState_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostStateClient) Put(ctx context.Context, in *StatePutRequest, opts ...grpc.CallOption) (*StatePutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatePutResponse)
	err := c.cc.Invoke(ctx, HostState_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostStateServer is the server API for HostState service.
// All implementations must embed UnimplementedHostStateServer
// for forward compatibility.
//
// HostState is a persistent, per-plugin byte store. It lets a sandboxed
// plugin remember opaque bytes across restarts (SSH host keys, signing
// material, a dynamic client_id) without a writable filesystem. The
// gateway namespaces every entry by the calling plugin, so one plugin
// can never read or write another's keys; the namespace is gateway-
// assigned, never sent by the plugin.
type HostStateServer interface {
	// Get returns the stored value for key, or found=false.
	Get(context.Context, *StateGetRequest) (*StateGetResponse, error)
	// Put stores value under key, overwriting any previous value.
	Put(context.Context, *StatePutRequest) (*StatePutResponse, error)
	mustEmbedUnimplementedHostStateServer()
}

// UnimplementedHostStateServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostStateServer struct{}

func (UnimplementedHostStateServer) Get(context.Context, *StateGetRequest) (*StateGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedHostStateServer) Put(context.Context, *StatePutRequest) (*StatePutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedHostStateServer) mustEmbedUnimplementedHostStateServer() {}
func (UnimplementedHostStateServer) testEmbeddedByValue()                   {}

// UnsafeHostStateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostStateServer will
// result in compilation errors.
type UnsafeHostStateServer interface {
	mustEmbedUnimplementedHostStateServer()
}

func RegisterHostStateServer(s grpc.ServiceRegistrar, srv HostStateServer) {
	// If the following call panics, it indicates UnimplementedHostStateServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostState_ServiceDesc, srv)
}

func _HostState_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostStateServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostState_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostStateServer).Get(ctx, req.(*StateGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostState_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatePutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostStateServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostState_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostStateServer).Put(ctx, req.(*StatePutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostState_ServiceDesc is the grpc.ServiceDesc for HostState service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostState_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clawpatrol.plugin.v1.HostState",
	HandlerType: (*HostStateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _HostState_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _HostState_Put_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

const (
	HostControl_Evaluate_FullMethodName = "/clawpatrol.plugin.v1.HostControl/Evaluate"
)

// HostControlClient is the client API for HostControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HostControl is the gateway's host-served control plane for plugin->host
// calls: the gateway serves it over the go-plugin broker (next to
// HostState) and a plugin calls it. Each plugin->gateway callback is an
// ordinary gRPC method, so gRPC correlates the reply and the hand-rolled
// call_id/dial_id inflight maps that ride inside HandleConn disappear. It
// grows by adding methods (Dial, HITL Decide), not new frames.
//
// Every call is scoped to one connection's evaluation context by the
// opaque session_token the gateway issued in that connection's ConnInit.
// The token rides in gRPC METADATA (key "clawpatrol-session"), not in the
// message — session scope is cross-cutting, so a server interceptor
// resolves it once and every method is scoped without repeating the field.
// A forged / expired / removed token is rejected before the handler runs.
type HostControlClient interface {
	// Evaluate runs the gateway's rule + approve chain for one action and
	// returns the verdict. The host-served replacement for the
	// EvaluateAction / ActionVerdict frames (and the inflight call_id map on
	// both sides of HandleConn). Stream-valued facet fields still use the
	// frame; inline actions use this.
	Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateVerdict, error)
}

type hostControlClient struct {
	cc grpc.ClientConnInterface
}

func NewHostControlClient(cc grpc.ClientConnInterface) HostControlClient {
	return &hostControlClient{cc}
}

func (c *hostControlClient) Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateVerdict, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateVerdict)
	err := c.cc.Invoke(ctx, HostControl_Evaluate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostControlServer is the server API for HostControl service.
// All implementations must embed UnimplementedHostControlServer
// for forward compatibility.
//
// HostControl is the gateway's host-served control plane for plugin->host
// calls: the gateway serves it over the go-plugin broker (next to
// HostState) and a plugin calls it. Each plugin->gateway callback is an
// ordinary gRPC method, so gRPC correlates the reply and the hand-rolled
// call_id/dial_id inflight maps that ride inside HandleConn disappear. It
// grows by adding methods (Dial, HITL Decide), not new frames.
//
// Every call is scoped to one connection's evaluation context by the
// opaque session_token the gateway issued in that connection's ConnInit.
// The token rides in gRPC METADATA (key "clawpatrol-session"), not in the
// message — session scope is cross-cutting, so a server interceptor
// resolves it once and every method is scoped without repeating the field.
// A forged / expired / removed token is rejected before the handler runs.
type HostControlServer interface {
	// Evaluate runs the gateway's rule + approve chain for one action and
	// returns the verdict. The host-served replacement for the
	// EvaluateAction / ActionVerdict frames (and the inflight call_id map on
	// both sides of HandleConn). Stream-valued facet fields still use the
	// frame; inline actions use this.
	Evaluate(context.Context, *EvaluateRequest) (*EvaluateVerdict, error)
	mustEmbedUnimplementedHostControlServer()
}

// UnimplementedHostControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostControlServer struct{}

func (UnimplementedHostControlServer) Evaluate(context.Context, *EvaluateRequest) (*EvaluateVerdict, error) {
	return nil, status.Error(codes.Unimplemented, "method Evaluate not implemented")
}
func (UnimplementedHostControlServer) mustEmbedUnimplementedHostControlServer() {}
func (UnimplementedHostControlServer) testEmbeddedByValue()                     {}

// UnsafeHostControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostControlServer will
// result in compilation errors.
type UnsafeHostControlServer interface {
	mustEmbedUnimplementedHostControlServer()
}

func RegisterHostControlServer(s grpc.ServiceRegistrar, srv HostControlServer) {
	// If the following call panics, it indicates UnimplementedHostControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostControl_ServiceDesc, srv)
}

func _HostControl_Evaluate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostControlServer).Evaluate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostControl_Evaluate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostControlServer).Evaluate(ctx, req.(*EvaluateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostControl_ServiceDesc is the grpc.ServiceDesc for HostControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clawpatrol.plugin.v1.HostControl",
	HandlerType: (*HostControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Evaluate",
			Handler:    _HostControl_Evaluate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

const (
	HostTunnel_DialUpstream_FullMethodName = "/clawpatrol.plugin.v1.HostTunnel/DialUpstream"
)

// HostTunnelClient is the client API for HostTunnel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HostTunnel is the brokered transport dial for tunnel plugins — the
// tunnel-side equivalent of an endpoint plugin's Conn.DialUpstream.
// Gateway-served, like HostState/HostControl: the plugin is the client.
// A tunnel plugin uses it to open the socket its transport rides on (the
// TCP conn to an SSH bastion, the UDP conn to a WireGuard endpoint)
// rather than opening a raw socket itself. The gateway routes the dial:
// directly when the tunnel is top-level, or through the PARENT tunnel
// when the tunnel is chained (`via = <tunnel>`). The plugin never knows
// the route — that's how WireGuard-over-SOCKS works without the WG plugin
// being SOCKS-aware. The gateway owns the composition.
type HostTunnelClient interface {
	// DialUpstream opens one transport connection for the calling tunnel.
	// The first DialMessage MUST be a DialInit whose tunnel_handle is the
	// transport_dial_handle from OpenTunnelRequest, and whose network/addr
	// name the target ("tcp"/"udp", "host:port"). For network="udp" the
	// byte stream carries length-prefixed datagrams (a 2-byte big-endian
	// length per packet); the gateway frames a real UDP socket on the
	// direct path, and a chained datagram tunnel (e.g. SOCKS5 UDP ASSOCIATE)
	// on the via path.
	DialUpstream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DialMessage, DialMessage], error)
}

type hostTunnelClient struct {
	cc grpc.ClientConnInterface
}

func NewHostTunnelClient(cc grpc.ClientConnInterface) HostTunnelClient {
	return &hostTunnelClient{cc}
}

func (c *hostTunnelClient) DialUpstream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DialMessage, DialMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HostTunnel_ServiceDesc.Streams[0], HostTunnel_DialUpstream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DialMessage, DialMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostTunnel_DialUpstreamClient = grpc.BidiStreamingClient[DialMessage, DialMessage]

// HostTunnelServer is the server API for HostTunnel service.
// All implementations must embed UnimplementedHostTunnelServer
// for forward compatibility.
//
// HostTunnel is the brokered transport dial for tunnel plugins — the
// tunnel-side equivalent of an endpoint plugin's Conn.DialUpstream.
// Gateway-served, like HostState/HostControl: the plugin is the client.
// A tunnel plugin uses it to open the socket its transport rides on (the
// TCP conn to an SSH bastion, the UDP conn to a WireGuard endpoint)
// rather than opening a raw socket itself. The gateway routes the dial:
// directly when the tunnel is top-level, or through the PARENT tunnel
// when the tunnel is chained (`via = <tunnel>`). The plugin never knows
// the route — that's how WireGuard-over-SOCKS works without the WG plugin
// being SOCKS-aware. The gateway owns the composition.
type HostTunnelServer interface {
	// DialUpstream opens one transport connection for the calling tunnel.
	// The first DialMessage MUST be a DialInit whose tunnel_handle is the
	// transport_dial_handle from OpenTunnelRequest, and whose network/addr
	// name the target ("tcp"/"udp", "host:port"). For network="udp" the
	// byte stream carries length-prefixed datagrams (a 2-byte big-endian
	// length per packet); the gateway frames a real UDP socket on the
	// direct path, and a chained datagram tunnel (e.g. SOCKS5 UDP ASSOCIATE)
	// on the via path.
	DialUpstream(grpc.BidiStreamingServer[DialMessage, DialMessage]) error
	mustEmbedUnimplementedHostTunnelServer()
}

// UnimplementedHostTunnelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostTunnelServer struct{}

func (UnimplementedHostTunnelServer) DialUpstream(grpc.BidiStreamingServer[DialMessage, DialMessage]) error {
	return status.Error(codes.Unimplemented, "method DialUpstream not implemented")
}
func (UnimplementedHostTunnelServer) mustEmbedUnimplementedHostTunnelServer() {}
func (UnimplementedHostTunnelServer) testEmbeddedByValue()                    {}

// UnsafeHostTunnelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostTunnelServer will
// result in compilation errors.
type UnsafeHostTunnelServer interface {
	mustEmbedUnimplementedHostTunnelServer()
}

func RegisterHostTunnelServer(s grpc.ServiceRegistrar, srv HostTunnelServer) {
	// If the following call panics, it indicates UnimplementedHostTunnelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostTunnel_ServiceDesc, srv)
}

func _HostTunnel_DialUpstream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HostTunnelServer).DialUpstream(&grpc.GenericServerStream[DialMessage, DialMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostTunnel_DialUpstreamServer = grpc.BidiStreamingServer[DialMessage, DialMessage]

// HostTunnel_ServiceDesc is the grpc.ServiceDesc for HostTunnel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostTunnel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clawpatrol.plugin.v1.HostTunnel",
	HandlerType: (*HostTunnelServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DialUpstream",
			Handler:       _HostTunnel_DialUpstream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "plugin.proto",
}
