// Plugin protocol v1 for clawpatrol's Terraform-style external plugins.
//
// One subprocess per plugin source. The gateway spawns the subprocess
// via hashicorp/go-plugin, fetches its Manifest, and registers virtual
// *config.Plugin entries for each declared (credential / tunnel /
// endpoint) type. At request time the gateway hands inbound conns to
// the plugin over the HandleConn bidi stream; endpoints that need an
// upstream connection through a tunnel go through Dial.
//
// The plugin is responsible for parsing whatever protocol rides on
// the bytes it receives. The gateway only optionally terminates TLS
// before handing the bytes over.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.6
// source: plugin.proto

package extpluginpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Plugin_Manifest_FullMethodName = "/clawpatrol.plugin.v1.Plugin/Manifest"
	Plugin_Build_FullMethodName    = "/clawpatrol.plugin.v1.Plugin/Build"
)

// PluginClient is the client API for Plugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginClient interface {
	// Manifest is called once on plugin startup. The plugin reports the
	// credential / tunnel / endpoint types it provides plus their HCL
	// schemas. The gateway converts each entry into a virtual
	// *config.Plugin and registers it.
	Manifest(ctx context.Context, in *ManifestRequest, opts ...grpc.CallOption) (*ManifestResponse, error)
	// Build is called once per HCL block during config load. The gateway
	// sends the decoded block body as a JSON object; the plugin
	// validates, normalizes, and returns canonical JSON that round-trips
	// back to the plugin in ConnInit / OpenTunnelRequest. Diagnostics
	// are reported back to the user with the block's source range.
	Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*BuildResponse, error)
}

type pluginClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginClient(cc grpc.ClientConnInterface) PluginClient {
	return &pluginClient{cc}
}

func (c *pluginClient) Manifest(ctx context.Context, in *ManifestRequest, opts ...grpc.CallOption) (*ManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManifestResponse)
	err := c.cc.Invoke(ctx, Plugin_Manifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*BuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildResponse)
	err := c.cc.Invoke(ctx, Plugin_Build_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServer is the server API for Plugin service.
// All implementations must embed UnimplementedPluginServer
// for forward compatibility.
type PluginServer interface {
	// Manifest is called once on plugin startup. The plugin reports the
	// credential / tunnel / endpoint types it provides plus their HCL
	// schemas. The gateway converts each entry into a virtual
	// *config.Plugin and registers it.
	Manifest(context.Context, *ManifestRequest) (*ManifestResponse, error)
	// Build is called once per HCL block during config load. The gateway
	// sends the decoded block body as a JSON object; the plugin
	// validates, normalizes, and returns canonical JSON that round-trips
	// back to the plugin in ConnInit / OpenTunnelRequest. Diagnostics
	// are reported back to the user with the block's source range.
	Build(context.Context, *BuildRequest) (*BuildResponse, error)
	mustEmbedUnimplementedPluginServer()
}

// UnimplementedPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginServer struct{}

func (UnimplementedPluginServer) Manifest(context.Context, *ManifestRequest) (*ManifestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Manifest not implemented")
}
func (UnimplementedPluginServer) Build(context.Context, *BuildRequest) (*BuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Build not implemented")
}
func (UnimplementedPluginServer) mustEmbedUnimplementedPluginServer() {}
func (UnimplementedPluginServer) testEmbeddedByValue()                {}

// UnsafePluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServer will
// result in compilation errors.
type UnsafePluginServer interface {
	mustEmbedUnimplementedPluginServer()
}

func RegisterPluginServer(s grpc.ServiceRegistrar, srv PluginServer) {
	// If the following call panics, it indicates UnimplementedPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Plugin_ServiceDesc, srv)
}

func _Plugin_Manifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Manifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_Manifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Manifest(ctx, req.(*ManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Build_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Build(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_Build_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Build(ctx, req.(*BuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Plugin_ServiceDesc is the grpc.ServiceDesc for Plugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Plugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clawpatrol.plugin.v1.Plugin",
	HandlerType: (*PluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Manifest",
			Handler:    _Plugin_Manifest_Handler,
		},
		{
			MethodName: "Build",
			Handler:    _Plugin_Build_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

const (
	Endpoint_HandleConn_FullMethodName = "/clawpatrol.plugin.v1.Endpoint/HandleConn"
)

// EndpointClient is the client API for Endpoint service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EndpointClient interface {
	// HandleConn is a bidi stream owning one inbound agent connection.
	//
	// Gateway sends ConnInit first, then ConnData frames as bytes arrive
	// from the agent. ConnClose from either side terminates the session.
	//
	// Plugin sends ConnData frames for bytes to write back to the agent,
	// and may interleave ConnEvent messages (audit emits).
	HandleConn(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConnMessage, ConnMessage], error)
}

type endpointClient struct {
	cc grpc.ClientConnInterface
}

func NewEndpointClient(cc grpc.ClientConnInterface) EndpointClient {
	return &endpointClient{cc}
}

func (c *endpointClient) HandleConn(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConnMessage, ConnMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Endpoint_ServiceDesc.Streams[0], Endpoint_HandleConn_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConnMessage, ConnMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Endpoint_HandleConnClient = grpc.BidiStreamingClient[ConnMessage, ConnMessage]

// EndpointServer is the server API for Endpoint service.
// All implementations must embed UnimplementedEndpointServer
// for forward compatibility.
type EndpointServer interface {
	// HandleConn is a bidi stream owning one inbound agent connection.
	//
	// Gateway sends ConnInit first, then ConnData frames as bytes arrive
	// from the agent. ConnClose from either side terminates the session.
	//
	// Plugin sends ConnData frames for bytes to write back to the agent,
	// and may interleave ConnEvent messages (audit emits).
	HandleConn(grpc.BidiStreamingServer[ConnMessage, ConnMessage]) error
	mustEmbedUnimplementedEndpointServer()
}

// UnimplementedEndpointServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEndpointServer struct{}

func (UnimplementedEndpointServer) HandleConn(grpc.BidiStreamingServer[ConnMessage, ConnMessage]) error {
	return status.Error(codes.Unimplemented, "method HandleConn not implemented")
}
func (UnimplementedEndpointServer) mustEmbedUnimplementedEndpointServer() {}
func (UnimplementedEndpointServer) testEmbeddedByValue()                  {}

// UnsafeEndpointServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EndpointServer will
// result in compilation errors.
type UnsafeEndpointServer interface {
	mustEmbedUnimplementedEndpointServer()
}

func RegisterEndpointServer(s grpc.ServiceRegistrar, srv EndpointServer) {
	// If the following call panics, it indicates UnimplementedEndpointServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Endpoint_ServiceDesc, srv)
}

func _Endpoint_HandleConn_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EndpointServer).HandleConn(&grpc.GenericServerStream[ConnMessage, ConnMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Endpoint_HandleConnServer = grpc.BidiStreamingServer[ConnMessage, ConnMessage]

// Endpoint_ServiceDesc is the grpc.ServiceDesc for Endpoint service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Endpoint_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clawpatrol.plugin.v1.Endpoint",
	HandlerType: (*EndpointServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HandleConn",
			Handler:       _Endpoint_HandleConn_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "plugin.proto",
}

const (
	Tunnel_OpenTunnel_FullMethodName  = "/clawpatrol.plugin.v1.Tunnel/OpenTunnel"
	Tunnel_Dial_FullMethodName        = "/clawpatrol.plugin.v1.Tunnel/Dial"
	Tunnel_CloseTunnel_FullMethodName = "/clawpatrol.plugin.v1.Tunnel/CloseTunnel"
)

// TunnelClient is the client API for Tunnel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TunnelClient interface {
	// OpenTunnel asks the plugin to bring up one tunnel instance.
	// The plugin returns an opaque handle that the gateway uses in
	// subsequent Dial / CloseTunnel calls.
	OpenTunnel(ctx context.Context, in *OpenTunnelRequest, opts ...grpc.CallOption) (*OpenTunnelResponse, error)
	// Dial opens one upstream connection via an open tunnel. Bidi
	// stream pumps bytes between gateway and tunneled upstream.
	Dial(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DialMessage, DialMessage], error)
	// CloseTunnel tears down a tunnel handle.
	CloseTunnel(ctx context.Context, in *CloseTunnelRequest, opts ...grpc.CallOption) (*CloseTunnelResponse, error)
}

type tunnelClient struct {
	cc grpc.ClientConnInterface
}

func NewTunnelClient(cc grpc.ClientConnInterface) TunnelClient {
	return &tunnelClient{cc}
}

func (c *tunnelClient) OpenTunnel(ctx context.Context, in *OpenTunnelRequest, opts ...grpc.CallOption) (*OpenTunnelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenTunnelResponse)
	err := c.cc.Invoke(ctx, Tunnel_OpenTunnel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tunnelClient) Dial(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DialMessage, DialMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Tunnel_ServiceDesc.Streams[0], Tunnel_Dial_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DialMessage, DialMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tunnel_DialClient = grpc.BidiStreamingClient[DialMessage, DialMessage]

func (c *tunnelClient) CloseTunnel(ctx context.Context, in *CloseTunnelRequest, opts ...grpc.CallOption) (*CloseTunnelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseTunnelResponse)
	err := c.cc.Invoke(ctx, Tunnel_CloseTunnel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TunnelServer is the server API for Tunnel service.
// All implementations must embed UnimplementedTunnelServer
// for forward compatibility.
type TunnelServer interface {
	// OpenTunnel asks the plugin to bring up one tunnel instance.
	// The plugin returns an opaque handle that the gateway uses in
	// subsequent Dial / CloseTunnel calls.
	OpenTunnel(context.Context, *OpenTunnelRequest) (*OpenTunnelResponse, error)
	// Dial opens one upstream connection via an open tunnel. Bidi
	// stream pumps bytes between gateway and tunneled upstream.
	Dial(grpc.BidiStreamingServer[DialMessage, DialMessage]) error
	// CloseTunnel tears down a tunnel handle.
	CloseTunnel(context.Context, *CloseTunnelRequest) (*CloseTunnelResponse, error)
	mustEmbedUnimplementedTunnelServer()
}

// UnimplementedTunnelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTunnelServer struct{}

func (UnimplementedTunnelServer) OpenTunnel(context.Context, *OpenTunnelRequest) (*OpenTunnelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenTunnel not implemented")
}
func (UnimplementedTunnelServer) Dial(grpc.BidiStreamingServer[DialMessage, DialMessage]) error {
	return status.Error(codes.Unimplemented, "method Dial not implemented")
}
func (UnimplementedTunnelServer) CloseTunnel(context.Context, *CloseTunnelRequest) (*CloseTunnelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseTunnel not implemented")
}
func (UnimplementedTunnelServer) mustEmbedUnimplementedTunnelServer() {}
func (UnimplementedTunnelServer) testEmbeddedByValue()                {}

// UnsafeTunnelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TunnelServer will
// result in compilation errors.
type UnsafeTunnelServer interface {
	mustEmbedUnimplementedTunnelServer()
}

func RegisterTunnelServer(s grpc.ServiceRegistrar, srv TunnelServer) {
	// If the following call panics, it indicates UnimplementedTunnelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tunnel_ServiceDesc, srv)
}

func _Tunnel_OpenTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenTunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelServer).OpenTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tunnel_OpenTunnel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelServer).OpenTunnel(ctx, req.(*OpenTunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tunnel_Dial_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TunnelServer).Dial(&grpc.GenericServerStream[DialMessage, DialMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tunnel_DialServer = grpc.BidiStreamingServer[DialMessage, DialMessage]

func _Tunnel_CloseTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseTunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelServer).CloseTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tunnel_CloseTunnel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelServer).CloseTunnel(ctx, req.(*CloseTunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Tunnel_ServiceDesc is the grpc.ServiceDesc for Tunnel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tunnel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clawpatrol.plugin.v1.Tunnel",
	HandlerType: (*TunnelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenTunnel",
			Handler:    _Tunnel_OpenTunnel_Handler,
		},
		{
			MethodName: "CloseTunnel",
			Handler:    _Tunnel_CloseTunnel_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Dial",
			Handler:       _Tunnel_Dial_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "plugin.proto",
}
