// Plugin protocol v1 for clawpatrol's Terraform-style external plugins.
//
// One subprocess per plugin source. The gateway spawns the subprocess
// via hashicorp/go-plugin, fetches its Manifest, and registers virtual
// *config.Plugin entries for each declared (credential / tunnel /
// endpoint) type. At request time the gateway hands inbound conns to
// the plugin over the HandleConn bidi stream; endpoints that need an
// upstream connection through a tunnel go through Dial.
//
// The plugin is responsible for parsing whatever protocol rides on
// the bytes it receives. The gateway only optionally terminates TLS
// before handing the bytes over.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: plugin.proto

package extpluginpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FacetKind int32

const (
	FacetKind_FACET_STRING      FacetKind = 0
	FacetKind_FACET_STRING_LIST FacetKind = 1
	FacetKind_FACET_STRING_MAP  FacetKind = 2
	FacetKind_FACET_INT         FacetKind = 3
	// FACET_STREAM is a lazy bytes value the plugin offers via a
	// handle in EvaluateAction.streams. The gateway pulls chunks via
	// StreamRead — fully when any endpoint rule references the
	// field, otherwise just enough to log a prefix — and sends
	// StreamCancel when it has what it needs. The plugin sees the
	// cancel and can stop buffering.
	FacetKind_FACET_STREAM FacetKind = 4
)

// Enum value maps for FacetKind.
var (
	FacetKind_name = map[int32]string{
		0: "FACET_STRING",
		1: "FACET_STRING_LIST",
		2: "FACET_STRING_MAP",
		3: "FACET_INT",
		4: "FACET_STREAM",
	}
	FacetKind_value = map[string]int32{
		"FACET_STRING":      0,
		"FACET_STRING_LIST": 1,
		"FACET_STRING_MAP":  2,
		"FACET_INT":         3,
		"FACET_STREAM":      4,
	}
)

func (x FacetKind) Enum() *FacetKind {
	p := new(FacetKind)
	*p = x
	return p
}

func (x FacetKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FacetKind) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[0].Descriptor()
}

func (FacetKind) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[0]
}

func (x FacetKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FacetKind.Descriptor instead.
func (FacetKind) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

type TLSMode int32

const (
	// No TLS handling on the inbound side. The plugin receives the raw
	// TCP bytes.
	TLSMode_TLS_NONE TLSMode = 0
	// Gateway terminates TLS using its CA, then hands the plaintext
	// bytes to the plugin via the HandleConn stream.
	TLSMode_TLS_TERMINATE TLSMode = 1
)

// Enum value maps for TLSMode.
var (
	TLSMode_name = map[int32]string{
		0: "TLS_NONE",
		1: "TLS_TERMINATE",
	}
	TLSMode_value = map[string]int32{
		"TLS_NONE":      0,
		"TLS_TERMINATE": 1,
	}
)

func (x TLSMode) Enum() *TLSMode {
	p := new(TLSMode)
	*p = x
	return p
}

func (x TLSMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TLSMode) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[1].Descriptor()
}

func (TLSMode) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[1]
}

func (x TLSMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TLSMode.Descriptor instead.
func (TLSMode) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

type Diagnostic_Severity int32

const (
	Diagnostic_ERROR   Diagnostic_Severity = 0
	Diagnostic_WARNING Diagnostic_Severity = 1
)

// Enum value maps for Diagnostic_Severity.
var (
	Diagnostic_Severity_name = map[int32]string{
		0: "ERROR",
		1: "WARNING",
	}
	Diagnostic_Severity_value = map[string]int32{
		"ERROR":   0,
		"WARNING": 1,
	}
)

func (x Diagnostic_Severity) Enum() *Diagnostic_Severity {
	p := new(Diagnostic_Severity)
	*p = x
	return p
}

func (x Diagnostic_Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Diagnostic_Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[2].Descriptor()
}

func (Diagnostic_Severity) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[2]
}

func (x Diagnostic_Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Diagnostic_Severity.Descriptor instead.
func (Diagnostic_Severity) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{11, 0}
}

type ManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestRequest) Reset() {
	*x = ManifestRequest{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestRequest) ProtoMessage() {}

func (x *ManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestRequest.ProtoReflect.Descriptor instead.
func (*ManifestRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

type ManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Credentials   []*CredentialDecl      `protobuf:"bytes,3,rep,name=credentials,proto3" json:"credentials,omitempty"`
	Tunnels       []*TunnelDecl          `protobuf:"bytes,4,rep,name=tunnels,proto3" json:"tunnels,omitempty"`
	Endpoints     []*EndpointDecl        `protobuf:"bytes,5,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Facets        []*FacetDecl           `protobuf:"bytes,6,rep,name=facets,proto3" json:"facets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestResponse) Reset() {
	*x = ManifestResponse{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestResponse) ProtoMessage() {}

func (x *ManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestResponse.ProtoReflect.Descriptor instead.
func (*ManifestResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *ManifestResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ManifestResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ManifestResponse) GetCredentials() []*CredentialDecl {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *ManifestResponse) GetTunnels() []*TunnelDecl {
	if x != nil {
		return x.Tunnels
	}
	return nil
}

func (x *ManifestResponse) GetEndpoints() []*EndpointDecl {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *ManifestResponse) GetFacets() []*FacetDecl {
	if x != nil {
		return x.Facets
	}
	return nil
}

// FacetDecl describes one protocol-family schema the plugin exports.
// The gateway registers a facet.Runtime per declared facet so the
// dashboard's /api/facets surfaces it and rules can compile CEL
// conditions against the declared fields. The facet's name is
// auto-namespaced by the gateway as "<plugin>.<name>".
type FacetDecl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fields        []*FacetFieldDecl      `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FacetDecl) Reset() {
	*x = FacetDecl{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FacetDecl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FacetDecl) ProtoMessage() {}

func (x *FacetDecl) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FacetDecl.ProtoReflect.Descriptor instead.
func (*FacetDecl) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *FacetDecl) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FacetDecl) GetFields() []*FacetFieldDecl {
	if x != nil {
		return x.Fields
	}
	return nil
}

type FacetFieldDecl struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind  FacetKind              `protobuf:"varint,2,opt,name=kind,proto3,enum=clawpatrol.plugin.v1.FacetKind" json:"kind,omitempty"`
	Label string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	// optional fields may be omitted from EvaluateAction.action_json.
	// The gateway substitutes a kind-zero value (empty string, empty
	// list, empty map, 0) before CEL evaluation so rule conditions
	// can reference them without `has()` guards.
	Optional      bool `protobuf:"varint,4,opt,name=optional,proto3" json:"optional,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FacetFieldDecl) Reset() {
	*x = FacetFieldDecl{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FacetFieldDecl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FacetFieldDecl) ProtoMessage() {}

func (x *FacetFieldDecl) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FacetFieldDecl.ProtoReflect.Descriptor instead.
func (*FacetFieldDecl) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *FacetFieldDecl) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FacetFieldDecl) GetKind() FacetKind {
	if x != nil {
		return x.Kind
	}
	return FacetKind_FACET_STRING
}

func (x *FacetFieldDecl) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *FacetFieldDecl) GetOptional() bool {
	if x != nil {
		return x.Optional
	}
	return false
}

// Schema is a flat list of attributes the plugin's HCL block accepts.
// Nested blocks are not supported in v1.
type Schema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*SchemaField         `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema) Reset() {
	*x = Schema{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *Schema) GetFields() []*SchemaField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type SchemaField struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// type_string is a go-cty type string, e.g. "string", "bool",
	// "number", "list(string)". The gateway decodes the HCL block
	// against this synthesized cty.Object before marshaling to JSON.
	TypeString    string `protobuf:"bytes,2,opt,name=type_string,json=typeString,proto3" json:"type_string,omitempty"`
	Required      bool   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaField) Reset() {
	*x = SchemaField{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaField) ProtoMessage() {}

func (x *SchemaField) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaField.ProtoReflect.Descriptor instead.
func (*SchemaField) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *SchemaField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SchemaField) GetTypeString() string {
	if x != nil {
		return x.TypeString
	}
	return ""
}

func (x *SchemaField) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

type CredentialDecl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeName      string                 `protobuf:"bytes,1,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	Schema        *Schema                `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialDecl) Reset() {
	*x = CredentialDecl{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialDecl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialDecl) ProtoMessage() {}

func (x *CredentialDecl) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialDecl.ProtoReflect.Descriptor instead.
func (*CredentialDecl) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *CredentialDecl) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *CredentialDecl) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

type TunnelDecl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeName      string                 `protobuf:"bytes,1,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	Schema        *Schema                `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelDecl) Reset() {
	*x = TunnelDecl{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelDecl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelDecl) ProtoMessage() {}

func (x *TunnelDecl) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelDecl.ProtoReflect.Descriptor instead.
func (*TunnelDecl) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *TunnelDecl) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *TunnelDecl) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

type EndpointDecl struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TypeName string                 `protobuf:"bytes,1,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	Schema   *Schema                `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	// family is forwarded to *config.Plugin.Family. Plugin endpoints
	// typically declare "stream" so rules can't accidentally target
	// them with http.* / sql.* matchers.
	Family        string  `protobuf:"bytes,3,opt,name=family,proto3" json:"family,omitempty"`
	TlsMode       TLSMode `protobuf:"varint,4,opt,name=tls_mode,json=tlsMode,proto3,enum=clawpatrol.plugin.v1.TLSMode" json:"tls_mode,omitempty"`
	RequiresVip   bool    `protobuf:"varint,5,opt,name=requires_vip,json=requiresVip,proto3" json:"requires_vip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointDecl) Reset() {
	*x = EndpointDecl{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointDecl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointDecl) ProtoMessage() {}

func (x *EndpointDecl) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointDecl.ProtoReflect.Descriptor instead.
func (*EndpointDecl) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *EndpointDecl) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *EndpointDecl) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *EndpointDecl) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

func (x *EndpointDecl) GetTlsMode() TLSMode {
	if x != nil {
		return x.TlsMode
	}
	return TLSMode_TLS_NONE
}

func (x *EndpointDecl) GetRequiresVip() bool {
	if x != nil {
		return x.RequiresVip
	}
	return false
}

type BuildRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kind is "credential", "tunnel", or "endpoint".
	Kind         string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	TypeName     string `protobuf:"bytes,2,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	InstanceName string `protobuf:"bytes,3,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	// config_json is a JSON object: the HCL block body decoded against
	// the plugin-declared schema, then marshaled via cty/json.
	ConfigJson    []byte `protobuf:"bytes,4,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildRequest) Reset() {
	*x = BuildRequest{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildRequest) ProtoMessage() {}

func (x *BuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildRequest.ProtoReflect.Descriptor instead.
func (*BuildRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *BuildRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *BuildRequest) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *BuildRequest) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *BuildRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

type BuildResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// canonical_json is the plugin's normalized form. The gateway
	// treats it as opaque; it's only forwarded back to the plugin in
	// ConnInit / OpenTunnelRequest.
	CanonicalJson []byte        `protobuf:"bytes,1,opt,name=canonical_json,json=canonicalJson,proto3" json:"canonical_json,omitempty"`
	Diagnostics   []*Diagnostic `protobuf:"bytes,2,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildResponse) Reset() {
	*x = BuildResponse{}
	mi := &file_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildResponse) ProtoMessage() {}

func (x *BuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildResponse.ProtoReflect.Descriptor instead.
func (*BuildResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *BuildResponse) GetCanonicalJson() []byte {
	if x != nil {
		return x.CanonicalJson
	}
	return nil
}

func (x *BuildResponse) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type Diagnostic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Severity      Diagnostic_Severity    `protobuf:"varint,1,opt,name=severity,proto3,enum=clawpatrol.plugin.v1.Diagnostic_Severity" json:"severity,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diagnostic) Reset() {
	*x = Diagnostic{}
	mi := &file_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostic) ProtoMessage() {}

func (x *Diagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostic.ProtoReflect.Descriptor instead.
func (*Diagnostic) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *Diagnostic) GetSeverity() Diagnostic_Severity {
	if x != nil {
		return x.Severity
	}
	return Diagnostic_ERROR
}

func (x *Diagnostic) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Diagnostic) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type ConnMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ConnMessage_Init
	//	*ConnMessage_Data
	//	*ConnMessage_Close
	//	*ConnMessage_Event
	//	*ConnMessage_Evaluate
	//	*ConnMessage_Verdict
	//	*ConnMessage_StreamRead
	//	*ConnMessage_StreamChunk
	//	*ConnMessage_StreamCancel
	Kind          isConnMessage_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnMessage) Reset() {
	*x = ConnMessage{}
	mi := &file_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnMessage) ProtoMessage() {}

func (x *ConnMessage) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnMessage.ProtoReflect.Descriptor instead.
func (*ConnMessage) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *ConnMessage) GetKind() isConnMessage_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ConnMessage) GetInit() *ConnInit {
	if x != nil {
		if x, ok := x.Kind.(*ConnMessage_Init); ok {
			return x.Init
		}
	}
	return nil
}

func (x *ConnMessage) GetData() *ConnData {
	if x != nil {
		if x, ok := x.Kind.(*ConnMessage_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *ConnMessage) GetClose() *ConnClose {
	if x != nil {
		if x, ok := x.Kind.(*ConnMessage_Close); ok {
			return x.Close
		}
	}
	return nil
}

func (x *ConnMessage) GetEvent() *ConnEvent {
	if x != nil {
		if x, ok := x.Kind.(*ConnMessage_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *ConnMessage) GetEvaluate() *EvaluateAction {
	if x != nil {
		if x, ok := x.Kind.(*ConnMessage_Evaluate); ok {
			return x.Evaluate
		}
	}
	return nil
}

func (x *ConnMessage) GetVerdict() *ActionVerdict {
	if x != nil {
		if x, ok := x.Kind.(*ConnMessage_Verdict); ok {
			return x.Verdict
		}
	}
	return nil
}

func (x *ConnMessage) GetStreamRead() *StreamRead {
	if x != nil {
		if x, ok := x.Kind.(*ConnMessage_StreamRead); ok {
			return x.StreamRead
		}
	}
	return nil
}

func (x *ConnMessage) GetStreamChunk() *StreamChunk {
	if x != nil {
		if x, ok := x.Kind.(*ConnMessage_StreamChunk); ok {
			return x.StreamChunk
		}
	}
	return nil
}

func (x *ConnMessage) GetStreamCancel() *StreamCancel {
	if x != nil {
		if x, ok := x.Kind.(*ConnMessage_StreamCancel); ok {
			return x.StreamCancel
		}
	}
	return nil
}

type isConnMessage_Kind interface {
	isConnMessage_Kind()
}

type ConnMessage_Init struct {
	Init *ConnInit `protobuf:"bytes,1,opt,name=init,proto3,oneof"`
}

type ConnMessage_Data struct {
	Data *ConnData `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type ConnMessage_Close struct {
	Close *ConnClose `protobuf:"bytes,3,opt,name=close,proto3,oneof"`
}

type ConnMessage_Event struct {
	Event *ConnEvent `protobuf:"bytes,4,opt,name=event,proto3,oneof"`
}

type ConnMessage_Evaluate struct {
	Evaluate *EvaluateAction `protobuf:"bytes,5,opt,name=evaluate,proto3,oneof"` // plugin -> gateway
}

type ConnMessage_Verdict struct {
	Verdict *ActionVerdict `protobuf:"bytes,6,opt,name=verdict,proto3,oneof"` // gateway -> plugin
}

type ConnMessage_StreamRead struct {
	StreamRead *StreamRead `protobuf:"bytes,7,opt,name=stream_read,json=streamRead,proto3,oneof"` // gateway -> plugin
}

type ConnMessage_StreamChunk struct {
	StreamChunk *StreamChunk `protobuf:"bytes,8,opt,name=stream_chunk,json=streamChunk,proto3,oneof"` // plugin -> gateway
}

type ConnMessage_StreamCancel struct {
	StreamCancel *StreamCancel `protobuf:"bytes,9,opt,name=stream_cancel,json=streamCancel,proto3,oneof"` // gateway -> plugin
}

func (*ConnMessage_Init) isConnMessage_Kind() {}

func (*ConnMessage_Data) isConnMessage_Kind() {}

func (*ConnMessage_Close) isConnMessage_Kind() {}

func (*ConnMessage_Event) isConnMessage_Kind() {}

func (*ConnMessage_Evaluate) isConnMessage_Kind() {}

func (*ConnMessage_Verdict) isConnMessage_Kind() {}

func (*ConnMessage_StreamRead) isConnMessage_Kind() {}

func (*ConnMessage_StreamChunk) isConnMessage_Kind() {}

func (*ConnMessage_StreamCancel) isConnMessage_Kind() {}

// StreamRead asks the plugin for the next chunk of an open stream.
// max_bytes is a hint; the plugin may return fewer bytes per chunk.
type StreamRead struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	MaxBytes      uint32                 `protobuf:"varint,2,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRead) Reset() {
	*x = StreamRead{}
	mi := &file_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRead) ProtoMessage() {}

func (x *StreamRead) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRead.ProtoReflect.Descriptor instead.
func (*StreamRead) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *StreamRead) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *StreamRead) GetMaxBytes() uint32 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

// StreamChunk delivers one chunk of stream data. eof signals that no
// more bytes will follow; the plugin needn't send a final empty
// chunk — eof can ride on the last data-bearing chunk.
type StreamChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Eof           bool                   `protobuf:"varint,3,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamChunk) Reset() {
	*x = StreamChunk{}
	mi := &file_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChunk) ProtoMessage() {}

func (x *StreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChunk.ProtoReflect.Descriptor instead.
func (*StreamChunk) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *StreamChunk) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *StreamChunk) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamChunk) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

// StreamCancel tells the plugin the gateway has read everything it
// needs and the plugin can drop its end of the stream. The plugin
// stops reading from its source io.Reader.
type StreamCancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamCancel) Reset() {
	*x = StreamCancel{}
	mi := &file_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamCancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCancel) ProtoMessage() {}

func (x *StreamCancel) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamCancel.ProtoReflect.Descriptor instead.
func (*StreamCancel) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *StreamCancel) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

// EvaluateAction asks the gateway to rule on one structured action
// (a "request" in the policy sense — an SMTP command, a query, an
// API call). The plugin sends the action's facet payload as JSON;
// the gateway runs the matched endpoint's compiled rules + any
// approve chain and replies with an ActionVerdict carrying the
// same call_id so plugins can pipeline concurrent calls.
type EvaluateAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// call_id is plugin-chosen and opaque; the gateway echoes it on
	// the matching ActionVerdict.
	CallId string `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// facet_name is the namespaced facet name ("<plugin>.<facet>")
	// whose schema action_json conforms to. Must match the endpoint's
	// declared family for the gateway to route through the right
	// CEL environment.
	FacetName string `protobuf:"bytes,2,opt,name=facet_name,json=facetName,proto3" json:"facet_name,omitempty"`
	// action_json is a JSON object whose keys match the facet's
	// declared scalar / list / map / int field names. Stream-typed
	// fields appear in `streams` instead.
	ActionJson []byte `protobuf:"bytes,3,opt,name=action_json,json=actionJson,proto3" json:"action_json,omitempty"`
	// summary is a human-readable one-liner the dashboard / HITL
	// prompt renders to describe what's being decided.
	Summary string `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	// streams maps each FACET_STREAM field name to a plugin-chosen
	// handle. The gateway issues StreamRead(handle, max_bytes) until
	// it has what it needs (full when a rule references the field,
	// log-prefix only otherwise) and then StreamCancel(handle).
	Streams       map[string]string `protobuf:"bytes,5,rep,name=streams,proto3" json:"streams,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateAction) Reset() {
	*x = EvaluateAction{}
	mi := &file_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateAction) ProtoMessage() {}

func (x *EvaluateAction) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateAction.ProtoReflect.Descriptor instead.
func (*EvaluateAction) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *EvaluateAction) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *EvaluateAction) GetFacetName() string {
	if x != nil {
		return x.FacetName
	}
	return ""
}

func (x *EvaluateAction) GetActionJson() []byte {
	if x != nil {
		return x.ActionJson
	}
	return nil
}

func (x *EvaluateAction) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *EvaluateAction) GetStreams() map[string]string {
	if x != nil {
		return x.Streams
	}
	return nil
}

type ActionVerdict struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"` // "allow" | "deny" | "hitl_allow" | "hitl_deny" | "error"
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Rule          string                 `protobuf:"bytes,4,opt,name=rule,proto3" json:"rule,omitempty"` // matched rule name, or "" when no rule fired
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionVerdict) Reset() {
	*x = ActionVerdict{}
	mi := &file_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionVerdict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionVerdict) ProtoMessage() {}

func (x *ActionVerdict) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionVerdict.ProtoReflect.Descriptor instead.
func (*ActionVerdict) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *ActionVerdict) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ActionVerdict) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ActionVerdict) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ActionVerdict) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

type ConnInit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifies which configured endpoint instance is being handled.
	EndpointTypeName string `protobuf:"bytes,1,opt,name=endpoint_type_name,json=endpointTypeName,proto3" json:"endpoint_type_name,omitempty"`
	EndpointInstance string `protobuf:"bytes,2,opt,name=endpoint_instance,json=endpointInstance,proto3" json:"endpoint_instance,omitempty"`
	// canonical_json is the BuildResponse.canonical_json for this
	// endpoint instance — the plugin's own normalized config.
	EndpointCanonicalJson []byte `protobuf:"bytes,3,opt,name=endpoint_canonical_json,json=endpointCanonicalJson,proto3" json:"endpoint_canonical_json,omitempty"`
	// Per-connection routing context.
	Profile      string `protobuf:"bytes,4,opt,name=profile,proto3" json:"profile,omitempty"`
	PeerIp       string `protobuf:"bytes,5,opt,name=peer_ip,json=peerIp,proto3" json:"peer_ip,omitempty"`
	UpstreamHost string `protobuf:"bytes,6,opt,name=upstream_host,json=upstreamHost,proto3" json:"upstream_host,omitempty"` // hostname recovered from VIP table
	DstPort      uint32 `protobuf:"varint,7,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	// Bound credential. credential_secret is the secret material
	// fetched by the gateway just-in-time from its secret store.
	// Empty when the endpoint has no credential.
	CredentialTypeName      string            `protobuf:"bytes,8,opt,name=credential_type_name,json=credentialTypeName,proto3" json:"credential_type_name,omitempty"`
	CredentialInstance      string            `protobuf:"bytes,9,opt,name=credential_instance,json=credentialInstance,proto3" json:"credential_instance,omitempty"`
	CredentialCanonicalJson []byte            `protobuf:"bytes,10,opt,name=credential_canonical_json,json=credentialCanonicalJson,proto3" json:"credential_canonical_json,omitempty"`
	CredentialSecret        []byte            `protobuf:"bytes,11,opt,name=credential_secret,json=credentialSecret,proto3" json:"credential_secret,omitempty"`
	CredentialExtras        map[string]string `protobuf:"bytes,12,rep,name=credential_extras,json=credentialExtras,proto3" json:"credential_extras,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Bound tunnel (optional). When set, the plugin can call Tunnel.Dial
	// on the host side using this handle to reach the upstream. v1 does
	// not implement reverse calls; the plugin uses its own net.Dial.
	TunnelTypeName string `protobuf:"bytes,13,opt,name=tunnel_type_name,json=tunnelTypeName,proto3" json:"tunnel_type_name,omitempty"`
	TunnelInstance string `protobuf:"bytes,14,opt,name=tunnel_instance,json=tunnelInstance,proto3" json:"tunnel_instance,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConnInit) Reset() {
	*x = ConnInit{}
	mi := &file_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnInit) ProtoMessage() {}

func (x *ConnInit) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnInit.ProtoReflect.Descriptor instead.
func (*ConnInit) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *ConnInit) GetEndpointTypeName() string {
	if x != nil {
		return x.EndpointTypeName
	}
	return ""
}

func (x *ConnInit) GetEndpointInstance() string {
	if x != nil {
		return x.EndpointInstance
	}
	return ""
}

func (x *ConnInit) GetEndpointCanonicalJson() []byte {
	if x != nil {
		return x.EndpointCanonicalJson
	}
	return nil
}

func (x *ConnInit) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *ConnInit) GetPeerIp() string {
	if x != nil {
		return x.PeerIp
	}
	return ""
}

func (x *ConnInit) GetUpstreamHost() string {
	if x != nil {
		return x.UpstreamHost
	}
	return ""
}

func (x *ConnInit) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *ConnInit) GetCredentialTypeName() string {
	if x != nil {
		return x.CredentialTypeName
	}
	return ""
}

func (x *ConnInit) GetCredentialInstance() string {
	if x != nil {
		return x.CredentialInstance
	}
	return ""
}

func (x *ConnInit) GetCredentialCanonicalJson() []byte {
	if x != nil {
		return x.CredentialCanonicalJson
	}
	return nil
}

func (x *ConnInit) GetCredentialSecret() []byte {
	if x != nil {
		return x.CredentialSecret
	}
	return nil
}

func (x *ConnInit) GetCredentialExtras() map[string]string {
	if x != nil {
		return x.CredentialExtras
	}
	return nil
}

func (x *ConnInit) GetTunnelTypeName() string {
	if x != nil {
		return x.TunnelTypeName
	}
	return ""
}

func (x *ConnInit) GetTunnelInstance() string {
	if x != nil {
		return x.TunnelInstance
	}
	return ""
}

type ConnData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnData) Reset() {
	*x = ConnData{}
	mi := &file_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnData) ProtoMessage() {}

func (x *ConnData) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnData.ProtoReflect.Descriptor instead.
func (*ConnData) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *ConnData) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ConnClose struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// optional reason; empty for a clean close.
	Reason        string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnClose) Reset() {
	*x = ConnClose{}
	mi := &file_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnClose) ProtoMessage() {}

func (x *ConnClose) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnClose.ProtoReflect.Descriptor instead.
func (*ConnClose) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *ConnClose) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ConnEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// action mirrors runtime.ConnEvent.Action: "allow" | "deny" |
	// "hitl_allow" | "hitl_deny" | "error".
	Action     string `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Reason     string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Verb       string `protobuf:"bytes,3,opt,name=verb,proto3" json:"verb,omitempty"`
	Summary    string `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	BytesCount int64  `protobuf:"varint,5,opt,name=bytes_count,json=bytesCount,proto3" json:"bytes_count,omitempty"`
	// facets_json is family-specific metadata. Treated as a JSON
	// object by the gateway and copied to Event.Facets.
	FacetsJson []byte `protobuf:"bytes,6,opt,name=facets_json,json=facetsJson,proto3" json:"facets_json,omitempty"`
	// rule, when non-empty, is the CompiledRule.Name the plugin
	// resolved internally. v1 plugins typically leave this empty.
	Rule          string `protobuf:"bytes,7,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnEvent) Reset() {
	*x = ConnEvent{}
	mi := &file_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnEvent) ProtoMessage() {}

func (x *ConnEvent) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnEvent.ProtoReflect.Descriptor instead.
func (*ConnEvent) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *ConnEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ConnEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ConnEvent) GetVerb() string {
	if x != nil {
		return x.Verb
	}
	return ""
}

func (x *ConnEvent) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ConnEvent) GetBytesCount() int64 {
	if x != nil {
		return x.BytesCount
	}
	return 0
}

func (x *ConnEvent) GetFacetsJson() []byte {
	if x != nil {
		return x.FacetsJson
	}
	return nil
}

func (x *ConnEvent) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

type OpenTunnelRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TunnelTypeName string                 `protobuf:"bytes,1,opt,name=tunnel_type_name,json=tunnelTypeName,proto3" json:"tunnel_type_name,omitempty"`
	TunnelInstance string                 `protobuf:"bytes,2,opt,name=tunnel_instance,json=tunnelInstance,proto3" json:"tunnel_instance,omitempty"`
	CanonicalJson  []byte                 `protobuf:"bytes,3,opt,name=canonical_json,json=canonicalJson,proto3" json:"canonical_json,omitempty"`
	// Optional credential bound to the tunnel.
	CredentialSecret []byte            `protobuf:"bytes,4,opt,name=credential_secret,json=credentialSecret,proto3" json:"credential_secret,omitempty"`
	CredentialExtras map[string]string `protobuf:"bytes,5,rep,name=credential_extras,json=credentialExtras,proto3" json:"credential_extras,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OpenTunnelRequest) Reset() {
	*x = OpenTunnelRequest{}
	mi := &file_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenTunnelRequest) ProtoMessage() {}

func (x *OpenTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenTunnelRequest.ProtoReflect.Descriptor instead.
func (*OpenTunnelRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *OpenTunnelRequest) GetTunnelTypeName() string {
	if x != nil {
		return x.TunnelTypeName
	}
	return ""
}

func (x *OpenTunnelRequest) GetTunnelInstance() string {
	if x != nil {
		return x.TunnelInstance
	}
	return ""
}

func (x *OpenTunnelRequest) GetCanonicalJson() []byte {
	if x != nil {
		return x.CanonicalJson
	}
	return nil
}

func (x *OpenTunnelRequest) GetCredentialSecret() []byte {
	if x != nil {
		return x.CredentialSecret
	}
	return nil
}

func (x *OpenTunnelRequest) GetCredentialExtras() map[string]string {
	if x != nil {
		return x.CredentialExtras
	}
	return nil
}

type OpenTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenTunnelResponse) Reset() {
	*x = OpenTunnelResponse{}
	mi := &file_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenTunnelResponse) ProtoMessage() {}

func (x *OpenTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenTunnelResponse.ProtoReflect.Descriptor instead.
func (*OpenTunnelResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{23}
}

func (x *OpenTunnelResponse) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

type CloseTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseTunnelRequest) Reset() {
	*x = CloseTunnelRequest{}
	mi := &file_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseTunnelRequest) ProtoMessage() {}

func (x *CloseTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseTunnelRequest.ProtoReflect.Descriptor instead.
func (*CloseTunnelRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{24}
}

func (x *CloseTunnelRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

type CloseTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseTunnelResponse) Reset() {
	*x = CloseTunnelResponse{}
	mi := &file_plugin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseTunnelResponse) ProtoMessage() {}

func (x *CloseTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseTunnelResponse.ProtoReflect.Descriptor instead.
func (*CloseTunnelResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{25}
}

type DialMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*DialMessage_Init
	//	*DialMessage_Data
	//	*DialMessage_Close
	Kind          isDialMessage_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DialMessage) Reset() {
	*x = DialMessage{}
	mi := &file_plugin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialMessage) ProtoMessage() {}

func (x *DialMessage) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialMessage.ProtoReflect.Descriptor instead.
func (*DialMessage) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{26}
}

func (x *DialMessage) GetKind() isDialMessage_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *DialMessage) GetInit() *DialInit {
	if x != nil {
		if x, ok := x.Kind.(*DialMessage_Init); ok {
			return x.Init
		}
	}
	return nil
}

func (x *DialMessage) GetData() *DialData {
	if x != nil {
		if x, ok := x.Kind.(*DialMessage_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *DialMessage) GetClose() *DialClose {
	if x != nil {
		if x, ok := x.Kind.(*DialMessage_Close); ok {
			return x.Close
		}
	}
	return nil
}

type isDialMessage_Kind interface {
	isDialMessage_Kind()
}

type DialMessage_Init struct {
	Init *DialInit `protobuf:"bytes,1,opt,name=init,proto3,oneof"`
}

type DialMessage_Data struct {
	Data *DialData `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type DialMessage_Close struct {
	Close *DialClose `protobuf:"bytes,3,opt,name=close,proto3,oneof"`
}

func (*DialMessage_Init) isDialMessage_Kind() {}

func (*DialMessage_Data) isDialMessage_Kind() {}

func (*DialMessage_Close) isDialMessage_Kind() {}

type DialInit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelHandle  string                 `protobuf:"bytes,1,opt,name=tunnel_handle,json=tunnelHandle,proto3" json:"tunnel_handle,omitempty"`
	Network       string                 `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DialInit) Reset() {
	*x = DialInit{}
	mi := &file_plugin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialInit) ProtoMessage() {}

func (x *DialInit) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialInit.ProtoReflect.Descriptor instead.
func (*DialInit) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{27}
}

func (x *DialInit) GetTunnelHandle() string {
	if x != nil {
		return x.TunnelHandle
	}
	return ""
}

func (x *DialInit) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *DialInit) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type DialData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DialData) Reset() {
	*x = DialData{}
	mi := &file_plugin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialData) ProtoMessage() {}

func (x *DialData) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialData.ProtoReflect.Descriptor instead.
func (*DialData) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{28}
}

func (x *DialData) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type DialClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DialClose) Reset() {
	*x = DialClose{}
	mi := &file_plugin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialClose) ProtoMessage() {}

func (x *DialClose) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialClose.ProtoReflect.Descriptor instead.
func (*DialClose) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{29}
}

func (x *DialClose) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x14clawpatrol.plugin.v1\"\x11\n" +
	"\x0fManifestRequest\"\xbf\x02\n" +
	"\x10ManifestResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12F\n" +
	"\vcredentials\x18\x03 \x03(\v2$.clawpatrol.plugin.v1.CredentialDeclR\vcredentials\x12:\n" +
	"\atunnels\x18\x04 \x03(\v2 .clawpatrol.plugin.v1.TunnelDeclR\atunnels\x12@\n" +
	"\tendpoints\x18\x05 \x03(\v2\".clawpatrol.plugin.v1.EndpointDeclR\tendpoints\x127\n" +
	"\x06facets\x18\x06 \x03(\v2\x1f.clawpatrol.plugin.v1.FacetDeclR\x06facets\"]\n" +
	"\tFacetDecl\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12<\n" +
	"\x06fields\x18\x02 \x03(\v2$.clawpatrol.plugin.v1.FacetFieldDeclR\x06fields\"\x8b\x01\n" +
	"\x0eFacetFieldDecl\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x123\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1f.clawpatrol.plugin.v1.FacetKindR\x04kind\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x1a\n" +
	"\boptional\x18\x04 \x01(\bR\boptional\"C\n" +
	"\x06Schema\x129\n" +
	"\x06fields\x18\x01 \x03(\v2!.clawpatrol.plugin.v1.SchemaFieldR\x06fields\"^\n" +
	"\vSchemaField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vtype_string\x18\x02 \x01(\tR\n" +
	"typeString\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\"c\n" +
	"\x0eCredentialDecl\x12\x1b\n" +
	"\ttype_name\x18\x01 \x01(\tR\btypeName\x124\n" +
	"\x06schema\x18\x02 \x01(\v2\x1c.clawpatrol.plugin.v1.SchemaR\x06schema\"_\n" +
	"\n" +
	"TunnelDecl\x12\x1b\n" +
	"\ttype_name\x18\x01 \x01(\tR\btypeName\x124\n" +
	"\x06schema\x18\x02 \x01(\v2\x1c.clawpatrol.plugin.v1.SchemaR\x06schema\"\xd6\x01\n" +
	"\fEndpointDecl\x12\x1b\n" +
	"\ttype_name\x18\x01 \x01(\tR\btypeName\x124\n" +
	"\x06schema\x18\x02 \x01(\v2\x1c.clawpatrol.plugin.v1.SchemaR\x06schema\x12\x16\n" +
	"\x06family\x18\x03 \x01(\tR\x06family\x128\n" +
	"\btls_mode\x18\x04 \x01(\x0e2\x1d.clawpatrol.plugin.v1.TLSModeR\atlsMode\x12!\n" +
	"\frequires_vip\x18\x05 \x01(\bR\vrequiresVip\"\x85\x01\n" +
	"\fBuildRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1b\n" +
	"\ttype_name\x18\x02 \x01(\tR\btypeName\x12#\n" +
	"\rinstance_name\x18\x03 \x01(\tR\finstanceName\x12\x1f\n" +
	"\vconfig_json\x18\x04 \x01(\fR\n" +
	"configJson\"z\n" +
	"\rBuildResponse\x12%\n" +
	"\x0ecanonical_json\x18\x01 \x01(\fR\rcanonicalJson\x12B\n" +
	"\vdiagnostics\x18\x02 \x03(\v2 .clawpatrol.plugin.v1.DiagnosticR\vdiagnostics\"\xa9\x01\n" +
	"\n" +
	"Diagnostic\x12E\n" +
	"\bseverity\x18\x01 \x01(\x0e2).clawpatrol.plugin.v1.Diagnostic.SeverityR\bseverity\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"\"\n" +
	"\bSeverity\x12\t\n" +
	"\x05ERROR\x10\x00\x12\v\n" +
	"\aWARNING\x10\x01\"\xd0\x04\n" +
	"\vConnMessage\x124\n" +
	"\x04init\x18\x01 \x01(\v2\x1e.clawpatrol.plugin.v1.ConnInitH\x00R\x04init\x124\n" +
	"\x04data\x18\x02 \x01(\v2\x1e.clawpatrol.plugin.v1.ConnDataH\x00R\x04data\x127\n" +
	"\x05close\x18\x03 \x01(\v2\x1f.clawpatrol.plugin.v1.ConnCloseH\x00R\x05close\x127\n" +
	"\x05event\x18\x04 \x01(\v2\x1f.clawpatrol.plugin.v1.ConnEventH\x00R\x05event\x12B\n" +
	"\bevaluate\x18\x05 \x01(\v2$.clawpatrol.plugin.v1.EvaluateActionH\x00R\bevaluate\x12?\n" +
	"\averdict\x18\x06 \x01(\v2#.clawpatrol.plugin.v1.ActionVerdictH\x00R\averdict\x12C\n" +
	"\vstream_read\x18\a \x01(\v2 .clawpatrol.plugin.v1.StreamReadH\x00R\n" +
	"streamRead\x12F\n" +
	"\fstream_chunk\x18\b \x01(\v2!.clawpatrol.plugin.v1.StreamChunkH\x00R\vstreamChunk\x12I\n" +
	"\rstream_cancel\x18\t \x01(\v2\".clawpatrol.plugin.v1.StreamCancelH\x00R\fstreamCancelB\x06\n" +
	"\x04kind\"A\n" +
	"\n" +
	"StreamRead\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\x12\x1b\n" +
	"\tmax_bytes\x18\x02 \x01(\rR\bmaxBytes\"Q\n" +
	"\vStreamChunk\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x10\n" +
	"\x03eof\x18\x03 \x01(\bR\x03eof\"&\n" +
	"\fStreamCancel\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\"\x8c\x02\n" +
	"\x0eEvaluateAction\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1d\n" +
	"\n" +
	"facet_name\x18\x02 \x01(\tR\tfacetName\x12\x1f\n" +
	"\vaction_json\x18\x03 \x01(\fR\n" +
	"actionJson\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12K\n" +
	"\astreams\x18\x05 \x03(\v21.clawpatrol.plugin.v1.EvaluateAction.StreamsEntryR\astreams\x1a:\n" +
	"\fStreamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"l\n" +
	"\rActionVerdict\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x12\n" +
	"\x04rule\x18\x04 \x01(\tR\x04rule\"\xd7\x05\n" +
	"\bConnInit\x12,\n" +
	"\x12endpoint_type_name\x18\x01 \x01(\tR\x10endpointTypeName\x12+\n" +
	"\x11endpoint_instance\x18\x02 \x01(\tR\x10endpointInstance\x126\n" +
	"\x17endpoint_canonical_json\x18\x03 \x01(\fR\x15endpointCanonicalJson\x12\x18\n" +
	"\aprofile\x18\x04 \x01(\tR\aprofile\x12\x17\n" +
	"\apeer_ip\x18\x05 \x01(\tR\x06peerIp\x12#\n" +
	"\rupstream_host\x18\x06 \x01(\tR\fupstreamHost\x12\x19\n" +
	"\bdst_port\x18\a \x01(\rR\adstPort\x120\n" +
	"\x14credential_type_name\x18\b \x01(\tR\x12credentialTypeName\x12/\n" +
	"\x13credential_instance\x18\t \x01(\tR\x12credentialInstance\x12:\n" +
	"\x19credential_canonical_json\x18\n" +
	" \x01(\fR\x17credentialCanonicalJson\x12+\n" +
	"\x11credential_secret\x18\v \x01(\fR\x10credentialSecret\x12a\n" +
	"\x11credential_extras\x18\f \x03(\v24.clawpatrol.plugin.v1.ConnInit.CredentialExtrasEntryR\x10credentialExtras\x12(\n" +
	"\x10tunnel_type_name\x18\r \x01(\tR\x0etunnelTypeName\x12'\n" +
	"\x0ftunnel_instance\x18\x0e \x01(\tR\x0etunnelInstance\x1aC\n" +
	"\x15CredentialExtrasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"$\n" +
	"\bConnData\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"#\n" +
	"\tConnClose\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\xbf\x01\n" +
	"\tConnEvent\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x12\n" +
	"\x04verb\x18\x03 \x01(\tR\x04verb\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x1f\n" +
	"\vbytes_count\x18\x05 \x01(\x03R\n" +
	"bytesCount\x12\x1f\n" +
	"\vfacets_json\x18\x06 \x01(\fR\n" +
	"facetsJson\x12\x12\n" +
	"\x04rule\x18\a \x01(\tR\x04rule\"\xeb\x02\n" +
	"\x11OpenTunnelRequest\x12(\n" +
	"\x10tunnel_type_name\x18\x01 \x01(\tR\x0etunnelTypeName\x12'\n" +
	"\x0ftunnel_instance\x18\x02 \x01(\tR\x0etunnelInstance\x12%\n" +
	"\x0ecanonical_json\x18\x03 \x01(\fR\rcanonicalJson\x12+\n" +
	"\x11credential_secret\x18\x04 \x01(\fR\x10credentialSecret\x12j\n" +
	"\x11credential_extras\x18\x05 \x03(\v2=.clawpatrol.plugin.v1.OpenTunnelRequest.CredentialExtrasEntryR\x10credentialExtras\x1aC\n" +
	"\x15CredentialExtrasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\",\n" +
	"\x12OpenTunnelResponse\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\",\n" +
	"\x12CloseTunnelRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\"\x15\n" +
	"\x13CloseTunnelResponse\"\xba\x01\n" +
	"\vDialMessage\x124\n" +
	"\x04init\x18\x01 \x01(\v2\x1e.clawpatrol.plugin.v1.DialInitH\x00R\x04init\x124\n" +
	"\x04data\x18\x02 \x01(\v2\x1e.clawpatrol.plugin.v1.DialDataH\x00R\x04data\x127\n" +
	"\x05close\x18\x03 \x01(\v2\x1f.clawpatrol.plugin.v1.DialCloseH\x00R\x05closeB\x06\n" +
	"\x04kind\"]\n" +
	"\bDialInit\x12#\n" +
	"\rtunnel_handle\x18\x01 \x01(\tR\ftunnelHandle\x12\x18\n" +
	"\anetwork\x18\x02 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x03 \x01(\tR\x04addr\"$\n" +
	"\bDialData\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"#\n" +
	"\tDialClose\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason*k\n" +
	"\tFacetKind\x12\x10\n" +
	"\fFACET_STRING\x10\x00\x12\x15\n" +
	"\x11FACET_STRING_LIST\x10\x01\x12\x14\n" +
	"\x10FACET_STRING_MAP\x10\x02\x12\r\n" +
	"\tFACET_INT\x10\x03\x12\x10\n" +
	"\fFACET_STREAM\x10\x04**\n" +
	"\aTLSMode\x12\f\n" +
	"\bTLS_NONE\x10\x00\x12\x11\n" +
	"\rTLS_TERMINATE\x10\x012\xb5\x01\n" +
	"\x06Plugin\x12Y\n" +
	"\bManifest\x12%.clawpatrol.plugin.v1.ManifestRequest\x1a&.clawpatrol.plugin.v1.ManifestResponse\x12P\n" +
	"\x05Build\x12\".clawpatrol.plugin.v1.BuildRequest\x1a#.clawpatrol.plugin.v1.BuildResponse2b\n" +
	"\bEndpoint\x12V\n" +
	"\n" +
	"HandleConn\x12!.clawpatrol.plugin.v1.ConnMessage\x1a!.clawpatrol.plugin.v1.ConnMessage(\x010\x012\x9f\x02\n" +
	"\x06Tunnel\x12_\n" +
	"\n" +
	"OpenTunnel\x12'.clawpatrol.plugin.v1.OpenTunnelRequest\x1a(.clawpatrol.plugin.v1.OpenTunnelResponse\x12P\n" +
	"\x04Dial\x12!.clawpatrol.plugin.v1.DialMessage\x1a!.clawpatrol.plugin.v1.DialMessage(\x010\x01\x12b\n" +
	"\vCloseTunnel\x12(.clawpatrol.plugin.v1.CloseTunnelRequest\x1a).clawpatrol.plugin.v1.CloseTunnelResponseBCZAgithub.com/denoland/clawpatrol/config/extplugin/proto;extpluginpbb\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_plugin_proto_goTypes = []any{
	(FacetKind)(0),              // 0: clawpatrol.plugin.v1.FacetKind
	(TLSMode)(0),                // 1: clawpatrol.plugin.v1.TLSMode
	(Diagnostic_Severity)(0),    // 2: clawpatrol.plugin.v1.Diagnostic.Severity
	(*ManifestRequest)(nil),     // 3: clawpatrol.plugin.v1.ManifestRequest
	(*ManifestResponse)(nil),    // 4: clawpatrol.plugin.v1.ManifestResponse
	(*FacetDecl)(nil),           // 5: clawpatrol.plugin.v1.FacetDecl
	(*FacetFieldDecl)(nil),      // 6: clawpatrol.plugin.v1.FacetFieldDecl
	(*Schema)(nil),              // 7: clawpatrol.plugin.v1.Schema
	(*SchemaField)(nil),         // 8: clawpatrol.plugin.v1.SchemaField
	(*CredentialDecl)(nil),      // 9: clawpatrol.plugin.v1.CredentialDecl
	(*TunnelDecl)(nil),          // 10: clawpatrol.plugin.v1.TunnelDecl
	(*EndpointDecl)(nil),        // 11: clawpatrol.plugin.v1.EndpointDecl
	(*BuildRequest)(nil),        // 12: clawpatrol.plugin.v1.BuildRequest
	(*BuildResponse)(nil),       // 13: clawpatrol.plugin.v1.BuildResponse
	(*Diagnostic)(nil),          // 14: clawpatrol.plugin.v1.Diagnostic
	(*ConnMessage)(nil),         // 15: clawpatrol.plugin.v1.ConnMessage
	(*StreamRead)(nil),          // 16: clawpatrol.plugin.v1.StreamRead
	(*StreamChunk)(nil),         // 17: clawpatrol.plugin.v1.StreamChunk
	(*StreamCancel)(nil),        // 18: clawpatrol.plugin.v1.StreamCancel
	(*EvaluateAction)(nil),      // 19: clawpatrol.plugin.v1.EvaluateAction
	(*ActionVerdict)(nil),       // 20: clawpatrol.plugin.v1.ActionVerdict
	(*ConnInit)(nil),            // 21: clawpatrol.plugin.v1.ConnInit
	(*ConnData)(nil),            // 22: clawpatrol.plugin.v1.ConnData
	(*ConnClose)(nil),           // 23: clawpatrol.plugin.v1.ConnClose
	(*ConnEvent)(nil),           // 24: clawpatrol.plugin.v1.ConnEvent
	(*OpenTunnelRequest)(nil),   // 25: clawpatrol.plugin.v1.OpenTunnelRequest
	(*OpenTunnelResponse)(nil),  // 26: clawpatrol.plugin.v1.OpenTunnelResponse
	(*CloseTunnelRequest)(nil),  // 27: clawpatrol.plugin.v1.CloseTunnelRequest
	(*CloseTunnelResponse)(nil), // 28: clawpatrol.plugin.v1.CloseTunnelResponse
	(*DialMessage)(nil),         // 29: clawpatrol.plugin.v1.DialMessage
	(*DialInit)(nil),            // 30: clawpatrol.plugin.v1.DialInit
	(*DialData)(nil),            // 31: clawpatrol.plugin.v1.DialData
	(*DialClose)(nil),           // 32: clawpatrol.plugin.v1.DialClose
	nil,                         // 33: clawpatrol.plugin.v1.EvaluateAction.StreamsEntry
	nil,                         // 34: clawpatrol.plugin.v1.ConnInit.CredentialExtrasEntry
	nil,                         // 35: clawpatrol.plugin.v1.OpenTunnelRequest.CredentialExtrasEntry
}
var file_plugin_proto_depIdxs = []int32{
	9,  // 0: clawpatrol.plugin.v1.ManifestResponse.credentials:type_name -> clawpatrol.plugin.v1.CredentialDecl
	10, // 1: clawpatrol.plugin.v1.ManifestResponse.tunnels:type_name -> clawpatrol.plugin.v1.TunnelDecl
	11, // 2: clawpatrol.plugin.v1.ManifestResponse.endpoints:type_name -> clawpatrol.plugin.v1.EndpointDecl
	5,  // 3: clawpatrol.plugin.v1.ManifestResponse.facets:type_name -> clawpatrol.plugin.v1.FacetDecl
	6,  // 4: clawpatrol.plugin.v1.FacetDecl.fields:type_name -> clawpatrol.plugin.v1.FacetFieldDecl
	0,  // 5: clawpatrol.plugin.v1.FacetFieldDecl.kind:type_name -> clawpatrol.plugin.v1.FacetKind
	8,  // 6: clawpatrol.plugin.v1.Schema.fields:type_name -> clawpatrol.plugin.v1.SchemaField
	7,  // 7: clawpatrol.plugin.v1.CredentialDecl.schema:type_name -> clawpatrol.plugin.v1.Schema
	7,  // 8: clawpatrol.plugin.v1.TunnelDecl.schema:type_name -> clawpatrol.plugin.v1.Schema
	7,  // 9: clawpatrol.plugin.v1.EndpointDecl.schema:type_name -> clawpatrol.plugin.v1.Schema
	1,  // 10: clawpatrol.plugin.v1.EndpointDecl.tls_mode:type_name -> clawpatrol.plugin.v1.TLSMode
	14, // 11: clawpatrol.plugin.v1.BuildResponse.diagnostics:type_name -> clawpatrol.plugin.v1.Diagnostic
	2,  // 12: clawpatrol.plugin.v1.Diagnostic.severity:type_name -> clawpatrol.plugin.v1.Diagnostic.Severity
	21, // 13: clawpatrol.plugin.v1.ConnMessage.init:type_name -> clawpatrol.plugin.v1.ConnInit
	22, // 14: clawpatrol.plugin.v1.ConnMessage.data:type_name -> clawpatrol.plugin.v1.ConnData
	23, // 15: clawpatrol.plugin.v1.ConnMessage.close:type_name -> clawpatrol.plugin.v1.ConnClose
	24, // 16: clawpatrol.plugin.v1.ConnMessage.event:type_name -> clawpatrol.plugin.v1.ConnEvent
	19, // 17: clawpatrol.plugin.v1.ConnMessage.evaluate:type_name -> clawpatrol.plugin.v1.EvaluateAction
	20, // 18: clawpatrol.plugin.v1.ConnMessage.verdict:type_name -> clawpatrol.plugin.v1.ActionVerdict
	16, // 19: clawpatrol.plugin.v1.ConnMessage.stream_read:type_name -> clawpatrol.plugin.v1.StreamRead
	17, // 20: clawpatrol.plugin.v1.ConnMessage.stream_chunk:type_name -> clawpatrol.plugin.v1.StreamChunk
	18, // 21: clawpatrol.plugin.v1.ConnMessage.stream_cancel:type_name -> clawpatrol.plugin.v1.StreamCancel
	33, // 22: clawpatrol.plugin.v1.EvaluateAction.streams:type_name -> clawpatrol.plugin.v1.EvaluateAction.StreamsEntry
	34, // 23: clawpatrol.plugin.v1.ConnInit.credential_extras:type_name -> clawpatrol.plugin.v1.ConnInit.CredentialExtrasEntry
	35, // 24: clawpatrol.plugin.v1.OpenTunnelRequest.credential_extras:type_name -> clawpatrol.plugin.v1.OpenTunnelRequest.CredentialExtrasEntry
	30, // 25: clawpatrol.plugin.v1.DialMessage.init:type_name -> clawpatrol.plugin.v1.DialInit
	31, // 26: clawpatrol.plugin.v1.DialMessage.data:type_name -> clawpatrol.plugin.v1.DialData
	32, // 27: clawpatrol.plugin.v1.DialMessage.close:type_name -> clawpatrol.plugin.v1.DialClose
	3,  // 28: clawpatrol.plugin.v1.Plugin.Manifest:input_type -> clawpatrol.plugin.v1.ManifestRequest
	12, // 29: clawpatrol.plugin.v1.Plugin.Build:input_type -> clawpatrol.plugin.v1.BuildRequest
	15, // 30: clawpatrol.plugin.v1.Endpoint.HandleConn:input_type -> clawpatrol.plugin.v1.ConnMessage
	25, // 31: clawpatrol.plugin.v1.Tunnel.OpenTunnel:input_type -> clawpatrol.plugin.v1.OpenTunnelRequest
	29, // 32: clawpatrol.plugin.v1.Tunnel.Dial:input_type -> clawpatrol.plugin.v1.DialMessage
	27, // 33: clawpatrol.plugin.v1.Tunnel.CloseTunnel:input_type -> clawpatrol.plugin.v1.CloseTunnelRequest
	4,  // 34: clawpatrol.plugin.v1.Plugin.Manifest:output_type -> clawpatrol.plugin.v1.ManifestResponse
	13, // 35: clawpatrol.plugin.v1.Plugin.Build:output_type -> clawpatrol.plugin.v1.BuildResponse
	15, // 36: clawpatrol.plugin.v1.Endpoint.HandleConn:output_type -> clawpatrol.plugin.v1.ConnMessage
	26, // 37: clawpatrol.plugin.v1.Tunnel.OpenTunnel:output_type -> clawpatrol.plugin.v1.OpenTunnelResponse
	29, // 38: clawpatrol.plugin.v1.Tunnel.Dial:output_type -> clawpatrol.plugin.v1.DialMessage
	28, // 39: clawpatrol.plugin.v1.Tunnel.CloseTunnel:output_type -> clawpatrol.plugin.v1.CloseTunnelResponse
	34, // [34:40] is the sub-list for method output_type
	28, // [28:34] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	file_plugin_proto_msgTypes[12].OneofWrappers = []any{
		(*ConnMessage_Init)(nil),
		(*ConnMessage_Data)(nil),
		(*ConnMessage_Close)(nil),
		(*ConnMessage_Event)(nil),
		(*ConnMessage_Evaluate)(nil),
		(*ConnMessage_Verdict)(nil),
		(*ConnMessage_StreamRead)(nil),
		(*ConnMessage_StreamChunk)(nil),
		(*ConnMessage_StreamCancel)(nil),
	}
	file_plugin_proto_msgTypes[26].OneofWrappers = []any{
		(*DialMessage_Init)(nil),
		(*DialMessage_Data)(nil),
		(*DialMessage_Close)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		EnumInfos:         file_plugin_proto_enumTypes,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
